const lang_ja = {
    title: "ワードウルフ",
    totalPlayers: "プレイヤー数",
    spyCount: "スパイ数",
    blankCount: "白紙数",
    customWordsToggle: "カスタムお題を使用",
    startGame: "ゲーム開始",
    customCivilianWord: "市民のお題",
    customSpyWord: "スパイのお題",
    playerReady: "私はプレイヤー{n}です",
    doNotShowOthers: "他の人には見せないでください。",
    blankWordPrompt: "あなたは白紙です。お題は分かりません。",
    iRemember: "覚えました",
    forgotWord: "お題を忘れた",
    execute: "処刑",
    spiesWin: "スパイの勝利！",
    civiliansWin: "市民の勝利！",
    restartSamePlayers: "同じメンバーで再戦",
    newGame: "新しいゲーム",
    languageChangeWarning: "ゲーム途中に言語を変更するとリセットされます。よろしいですか？",
    roleCivilian: "市民",
    roleSpy: "スパイ",
    roleBlank: "白紙",
    handToPlayerN: "プレイヤー{n}にスマホを渡す",
    resetGame: "ゲームをリセット",
    resetConfirmation: "ゲームをリセットしてもよろしいですか？",
    usingExistingPlayers: "既存のメンバーを使用 ({n})",
    thatsMe: "それは私です！",
    civiliansWinPrompt: "市民のお題は何だったのでしょう...？",
    spiesWinPrompt: "スパイの勝利！スパイの皆さん、市民のお題を推理できましたか？",
    spyWordLabel: "スパイのお題： ",
    seeResults: "結果を見る",
    showTranslation: "🇬🇧 英語の翻訳",
    showPronunciation: "🗣️ 発音を表示"
};
