const lang_ja = {
    title: "ワードウルフ (Who is Spy)",
    totalPlayers: "プレイヤー数",
    spyCount: "スパイ数",
    blankCount: "白紙数",
    customWordsToggle: "カスタムお題を使用",
    startGame: "ゲーム開始",
    playerCountWarning: "無効な設定です。",
    customCivilianWord: "市民のお題",
    customSpyWord: "スパイのお題",
    nextPlayer: "次のプレイヤーに渡す",
    playerReady: "私はプレイヤー{n}です",
    takeSelfieAndSeeWord: "覚えました、撮影する",
    doNotShowOthers: "他の人には見せないでください。",
    yourWordIs: "あなたのお題：",
    blankWordPrompt: "あなたは白紙です。お題は分かりません。",
    iRemember: "覚えました",
    playersRemaining: "残りのプレイヤー",
    selectPlayer: "プレイヤーを選択",
    forgotWord: "お題を忘れた",
    execute: "処刑",
    cancel: "キャンセル",
    eliminated: "脱落",
    civilian: "市民",
    spy: "スパイ",
    blank: "白紙",
    spiesWin: "スパイの勝利！",
    civiliansWin: "市民の勝利！",
    winningWordWas: "市民のお題：{civilian}。スパイのお題：{spy}。",
    restartSamePlayers: "同じメンバーで再戦",
    newGame: "新しいゲーム",
    languageChangeWarning: "ゲーム途中に言語を変更するとリセットされます。よろしいですか？",
    roleCivilian: "市民",
    roleSpy: "スパイ",
    roleBlank: "白紙",
    playDirection: "発言順：",
    directionForward: "時計回り \u2192",
    directionBackward: "\u2190 反時計回り",
    gamePhaseVoting: "話し合いと投票タイム",
    identityRevealed: "{player}は{role}でした！",
    handToPlayerN: "プレイヤー{n}にスマホを渡す",
    resetGame: "ゲームをリセット"
};
