const lang_zh_CN = {
    title: "谁是卧底",
    totalPlayers: "玩家总数",
    spyCount: "卧底人数",
    blankCount: "白板人数",
    customWordsToggle: "使用自定义词语",
    startGame: "开始游戏",
    playerCountWarning: "玩家配置无效。",
    customCivilianWord: "平民词",
    customSpyWord: "卧底词",
    nextPlayer: "传给下一位玩家",
    playerReady: "我是{n}号，拍照",
    takeSelfieAndSeeWord: "我记住了，拍照",
    doNotShowOthers: "请勿让别人看到。",
    yourWordIs: "你的词是：",
    blankWordPrompt: "你是白板，你不知道词是什么。",
    iRemember: "我记住了",
    playersRemaining: "剩余玩家",
    selectPlayer: "选择玩家",
    forgotWord: "我忘了我的词",
    execute: "处决",
    cancel: "取消",
    eliminated: "已出局",
    civilian: "平民",
    spy: "卧底",
    blank: "白板",
    spiesWin: "卧底胜利！",
    civiliansWin: "平民胜利！",
    winningWordWas: "平民词是：{civilian}。卧底词是：{spy}。",
    restartSamePlayers: "原班人马再来一局",
    newGame: "新游戏",
    languageChangeWarning: "游戏中途更改语言将重置游戏。确定继续吗？",
    roleCivilian: "平民",
    roleSpy: "卧底",
    roleBlank: "白板",
    playDirection: "发言顺序：",
    directionForward: "正序 \u2192",
    directionBackward: "\u2190 逆序",
    gamePhaseVoting: "讨论与投票阶段",
    identityRevealed: "{player} 是 {role}！",
    handToPlayerN: "请把手机给 {n}号玩家",
    resetGame: "重置游戏"
};
