const lang_zh_CN = {
    title: "谁是卧底",
    totalPlayers: "玩家总数",
    spyCount: "卧底人数",
    blankCount: "白板人数",
    customWordsToggle: "使用自定义词语",
    startGame: "开始游戏",
    customCivilianWord: "平民词",
    customSpyWord: "卧底词",
    playerReady: "我是{n}号，拍照",
    doNotShowOthers: "请勿让别人看到。",
    blankWordPrompt: "你是白板，你不知道词是什么。",
    iRemember: "我记住了",
    forgotWord: "我忘了我的词",
    execute: "处决",
    spiesWin: "卧底胜利！",
    civiliansWin: "平民胜利！",
    restartSamePlayers: "原班人马再来一局",
    newGame: "新游戏",
    languageChangeWarning: "游戏中途更改语言将重置游戏。确定继续吗？",
    roleCivilian: "平民",
    roleSpy: "卧底",
    roleBlank: "白板",
    handToPlayerN: "请把手机给 {n}号玩家",
    resetGame: "重置游戏",
    resetConfirmation: "确定要重置游戏吗？",
    usingExistingPlayers: "使用现有玩家 ({n})",
    thatsMe: "是我！",
    civiliansWinPrompt: "平民词到底是什么呢...？",
    spiesWinPrompt: "卧底胜利！卧底，你们猜出平民词了吗？",
    spyWordLabel: "卧底词： ",
    seeResults: "查看结果",
    showTranslation: "🇬🇧 英语翻译",
    showPronunciation: "🗣️ 显示发音",
    roundText: "回合",
    startText: "开始"
};
