const lang_zh_TW = {
    title: "誰是臥底",
    totalPlayers: "玩家總數",
    spyCount: "臥底人數",
    blankCount: "白板人數",
    customWordsToggle: "使用自定義詞語",
    startGame: "開始遊戲",
    playerCountWarning: "玩家配置無效。",
    customCivilianWord: "平民詞",
    customSpyWord: "臥底詞",
    nextPlayer: "傳給下一位玩家",
    playerReady: "我是{n}號，拍照",
    takeSelfieAndSeeWord: "我記住了，拍照",
    doNotShowOthers: "請勿讓別人看到。",
    yourWordIs: "你的詞是：",
    blankWordPrompt: "你是白板，你不知道詞是什麼。",
    iRemember: "我記住了",
    playersRemaining: "剩餘玩家",
    selectPlayer: "選擇玩家",
    forgotWord: "我忘了我的詞",
    execute: "處決",
    cancel: "取消",
    eliminated: "已出局",
    civilian: "平民",
    spy: "臥底",
    blank: "白板",
    spiesWin: "臥底勝利！",
    civiliansWin: "平民勝利！",
    winningWordWas: "平民詞是：{civilian}。臥底詞是：{spy}。",
    restartSamePlayers: "原班人馬再來一局",
    newGame: "新遊戲",
    languageChangeWarning: "遊戲中途更改語言將重置遊戲。確定繼續嗎？",
    roleCivilian: "平民",
    roleSpy: "臥底",
    roleBlank: "白板",
    playDirection: "發言順序：",
    directionForward: "正序 \u2192",
    directionBackward: "\u2190 逆序",
    gamePhaseVoting: "討論與投票階段",
    identityRevealed: "{player} 是 {role}！",
    handToPlayerN: "請把手機給 {n}號玩家",
    resetGame: "重置遊戲"
};
