const lang_en = {
    title: "Who is Spy?",
    totalPlayers: "Total Players",
    spyCount: "Spies",
    blankCount: "Blank Cards",
    customWordsToggle: "Use Custom Words",
    startGame: "Start Game",
    playerCountWarning: "Invalid player configuration.",
    customCivilianWord: "Civilian Word",
    customSpyWord: "Spy Word",
    nextPlayer: "Pass to next player",
    playerReady: "I'm Player {n}, take selfie",
    takeSelfieAndSeeWord: "I remember, take selfie",
    doNotShowOthers: "Do not show others.",
    yourWordIs: "Your word is:",
    blankWordPrompt: "You are the blank card, you do not get to know the word.",
    iRemember: "I remember",
    playersRemaining: "Players Remaining",
    selectPlayer: "Select Player",
    forgotWord: "I forgot my word",
    execute: "Execute",
    cancel: "Cancel",
    eliminated: "Eliminated",
    civilian: "Civilian",
    spy: "Spy",
    blank: "Blank Card",
    spiesWin: "Spies Win!",
    civiliansWin: "Civilians Win!",
    winningWordWas: "The civilian word was: {civilian}. The spy word was: {spy}.",
    restartSamePlayers: "Restart with same players",
    newGame: "New Game",
    languageChangeWarning: "Changing language mid-game will restart the game. Proceed?",
    roleCivilian: "Civilian",
    roleSpy: "Spy",
    roleBlank: "Blank Card",
    playDirection: "Play Direction: ",
    directionForward: "Forward \u2192",
    directionBackward: "\u2190 Backward",
    gamePhaseVoting: "Discussion & Voting Phase",
    identityRevealed: "{player} was a {role}!",
    handToPlayerN: "Hand the phone to Player {n}",
    resetGame: "Reset Game"
};
