const lang_en = {
    title: "Who is Spy?",
    totalPlayers: "Total Players",
    spyCount: "Spies",
    blankCount: "Blank Cards",
    customWordsToggle: "Use Custom Words",
    startGame: "Start Game",
    customCivilianWord: "Civilian Word",
    customSpyWord: "Spy Word",
    playerReady: "I'm Player {n}, take selfie",
    doNotShowOthers: "Do not show others.",
    blankWordPrompt: "You are the blank card, you do not get to know the word.",
    iRemember: "I remember",
    forgotWord: "I forgot my word",
    execute: "Execute",
    spiesWin: "Spies Win!",
    civiliansWin: "Civilians Win!",
    restartSamePlayers: "Restart with same players",
    newGame: "New Game",
    languageChangeWarning: "Changing language mid-game will restart the game. Proceed?",
    roleCivilian: "Civilian",
    roleSpy: "Spy",
    roleBlank: "Blank Card",
    handToPlayerN: "Hand the phone to Player {n}",
    resetGame: "Reset Game",
    usingExistingPlayers: "Using existing players ({n})",
    thatsMe: "That's me!",
    civiliansWinPrompt: "I wonder what the civilian word was...?",
    spiesWinPrompt: "The spies won! Spies, did you successfully deduce the civilian word?",
    spyWordLabel: "Spy word: "
};
