const lang_zh_TW = {
    title: "誰是臥底",
    totalPlayers: "玩家總數",
    spyCount: "臥底人數",
    blankCount: "白板人數",
    customWordsToggle: "使用自定義詞語",
    startGame: "開始遊戲",
    customCivilianWord: "平民詞",
    customSpyWord: "臥底詞",
    playerReady: "我是{n}號，拍照",
    doNotShowOthers: "請勿讓別人看到。",
    blankWordPrompt: "你是白板，你不知道詞是什麼。",
    iRemember: "我記住了",
    forgotWord: "我忘了我的詞",
    execute: "處決",
    spiesWin: "臥底勝利！",
    civiliansWin: "平民勝利！",
    restartSamePlayers: "原班人馬再來一局",
    newGame: "新遊戲",
    languageChangeWarning: "遊戲中途更改語言將重置遊戲。確定繼續嗎？",
    roleCivilian: "平民",
    roleSpy: "臥底",
    roleBlank: "白板",
    handToPlayerN: "請把手機給 {n}號玩家",
    resetGame: "重置遊戲",
    resetConfirmation: "確定要重置遊戲嗎？",
    usingExistingPlayers: "使用現有玩家 ({n})",
    thatsMe: "是我！",
    civiliansWinPrompt: "平民詞到底是什麼呢...？",
    spiesWinPrompt: "臥底勝利！臥底，你們猜出平民詞了嗎？",
    spyWordLabel: "臥底詞： ",
    seeResults: "查看結果",
    showTranslation: "🇬🇧 英文翻譯",
    showPronunciation: "🗣️ 顯示發音"
};
