const localization = {
  en: {
    title: "Who is Spy?",
    totalPlayers: "Total Players",
    spyCount: "Spies",
    blankCount: "Blank Cards",
    wordSource: "Word Source",
    randomWords: "Random Words",
    customWords: "Custom Words",
    startGame: "Start Game",
    playerCountWarning: "Invalid player configuration.",
    customCivilianWord: "Civilian Word",
    customSpyWord: "Spy Word",
    nextPlayer: "Pass to next player",
    playerReady: "I'm Player {n}, take selfie",
    takeSelfieAndSeeWord: "I remember, take selfie",
    photoTakenPrompt: "Photo taken. Now revealing your word. Do not show others.",
    yourWordIs: "Your word is:",
    spyWordPrompt: "You are the Spy. Try to blend in!",
    blankWordPrompt: "You are the blank card, you do not get to know the word.",
    iRemember: "I remember",
    playersRemaining: "Players Remaining",
    selectPlayer: "Select Player",
    forgotWord: "I forgot my word",
    execute: "Execute",
    cancel: "Cancel",
    eliminated: "Eliminated",
    civilian: "Civilian",
    spy: "Spy",
    blank: "Blank Card",
    spiesWin: "Spies Win!",
    civiliansWin: "Civilians Win!",
    winningWordWas: "The civilian word was: {civilian}. The spy word was: {spy}.",
    restartSamePlayers: "Restart with same players",
    newGame: "New Game",
    languageChangeWarning: "Changing language mid-game will restart the game. Proceed?",
    roleCivilian: "Civilian",
    roleSpy: "Spy",
    roleBlank: "Blank Card",
    playDirection: "Play Direction: ",
    directionForward: "Forward \u2192",
    directionBackward: "\u2190 Backward",
    confirmCustomWords: "Confirm Words",
    customWordsPrompt: "Hand the phone to a non-player to enter the words.",
    gamePhaseVoting: "Discussion & Voting Phase",
    identityRevealed: "{player} was a {role}!",
    handToPlayerN: "Hand the phone to Player {n}"
  },
  "zh-CN": {
    title: "谁是卧底",
    totalPlayers: "玩家总数",
    spyCount: "卧底人数",
    blankCount: "白板人数",
    wordSource: "词语来源",
    randomWords: "随机词库",
    customWords: "自定义词语",
    startGame: "开始游戏",
    playerCountWarning: "玩家配置无效。",
    customCivilianWord: "平民词",
    customSpyWord: "卧底词",
    nextPlayer: "传给下一位玩家",
    playerReady: "我是{n}号，拍照",
    takeSelfieAndSeeWord: "我记住了，拍照",
    photoTakenPrompt: "照片已拍。这里是你的词，请勿让别人看到。",
    yourWordIs: "你的词是：",
    spyWordPrompt: "你的词是：{word} (你是卧底，尽量隐藏自己！)",
    blankWordPrompt: "你是白板，你不知道词是什么。",
    iRemember: "我记住了",
    playersRemaining: "剩余玩家",
    selectPlayer: "选择玩家",
    forgotWord: "我忘了我的词",
    execute: "处决",
    cancel: "取消",
    eliminated: "已出局",
    civilian: "平民",
    spy: "卧底",
    blank: "白板",
    spiesWin: "卧底胜利！",
    civiliansWin: "平民胜利！",
    winningWordWas: "平民词是：{civilian}。卧底词是：{spy}。",
    restartSamePlayers: "原班人马再来一局",
    newGame: "新游戏",
    languageChangeWarning: "游戏中途更改语言将重置游戏。确定继续吗？",
    roleCivilian: "平民",
    roleSpy: "卧底",
    roleBlank: "白板",
    playDirection: "发言顺序：",
    directionForward: "正序 \u2192",
    directionBackward: "\u2190 逆序",
    confirmCustomWords: "确认自选词",
    customWordsPrompt: "请将手机交给非游戏玩家输入词语。",
    gamePhaseVoting: "讨论与投票阶段",
    identityRevealed: "{player} 是 {role}！",
    handToPlayerN: "请把手机给 {n}号玩家"
  },
  "zh-TW": {
    title: "誰是臥底",
    totalPlayers: "玩家總數",
    spyCount: "臥底人數",
    blankCount: "白板人數",
    wordSource: "詞語來源",
    randomWords: "隨機詞庫",
    customWords: "自定義詞語",
    startGame: "開始遊戲",
    playerCountWarning: "玩家配置無效。",
    customCivilianWord: "平民詞",
    customSpyWord: "臥底詞",
    nextPlayer: "傳給下一位玩家",
    playerReady: "我是{n}號，拍照",
    takeSelfieAndSeeWord: "我記住了，拍照",
    photoTakenPrompt: "照片已拍。這裡是你的詞，請勿讓別人看到。",
    yourWordIs: "你的詞是：",
    spyWordPrompt: "你的詞是：{word} (你是臥底，盡量隱藏自己！)",
    blankWordPrompt: "你是白板，你不知道詞是什麼。",
    iRemember: "我記住了",
    playersRemaining: "剩餘玩家",
    selectPlayer: "選擇玩家",
    forgotWord: "我忘了我的詞",
    execute: "處決",
    cancel: "取消",
    eliminated: "已出局",
    civilian: "平民",
    spy: "臥底",
    blank: "白板",
    spiesWin: "臥底勝利！",
    civiliansWin: "平民勝利！",
    winningWordWas: "平民詞是：{civilian}。臥底詞是：{spy}。",
    restartSamePlayers: "原班人馬再來一局",
    newGame: "新遊戲",
    languageChangeWarning: "遊戲中途更改語言將重置遊戲。確定繼續嗎？",
    roleCivilian: "平民",
    roleSpy: "臥底",
    roleBlank: "白板",
    playDirection: "發言順序：",
    directionForward: "正序 \u2192",
    directionBackward: "\u2190 逆序",
    confirmCustomWords: "確認自選詞",
    customWordsPrompt: "請將手機交給非遊戲玩家輸入詞語。",
    gamePhaseVoting: "討論與投票階段",
    identityRevealed: "{player} 是 {role}！",
    handToPlayerN: "請把手機給 {n}號玩家"
  },
  "ja": {
    title: "ワードウルフ (Who is Spy)",
    totalPlayers: "プレイヤー数",
    spyCount: "スパイ数",
    blankCount: "白紙（ブランク）数",
    wordSource: "お題の出所",
    randomWords: "ランダム",
    customWords: "カスタム",
    startGame: "ゲーム開始",
    playerCountWarning: "無効な設定です。",
    customCivilianWord: "市民のお題",
    customSpyWord: "スパイのお題",
    nextPlayer: "次のプレイヤーに渡す",
    playerReady: "私はプレイヤー{n}です",
    takeSelfieAndSeeWord: "覚えました、撮影する",
    photoTakenPrompt: "撮影完了。あなたのお題です。他の人には見せないでください。",
    yourWordIs: "あなたのお題：",
    spyWordPrompt: "あなたのお題：{word} (あなたはスパイです。うまく紛れ込んでください！)",
    blankWordPrompt: "あなたは白紙です。お題は分かりません。",
    iRemember: "覚えました",
    playersRemaining: "残りのプレイヤー",
    selectPlayer: "プレイヤーを選択",
    forgotWord: "お題を忘れた",
    execute: "処刑",
    cancel: "キャンセル",
    eliminated: "脱落",
    civilian: "市民",
    spy: "スパイ",
    blank: "白紙",
    spiesWin: "スパイの勝利！",
    civiliansWin: "市民の勝利！",
    winningWordWas: "市民のお題：{civilian}。スパイのお題：{spy}。",
    restartSamePlayers: "同じメンバーで再戦",
    newGame: "新しいゲーム",
    languageChangeWarning: "ゲーム途中に言語を変更するとリセットされます。よろしいですか？",
    roleCivilian: "市民",
    roleSpy: "スパイ",
    roleBlank: "白紙",
    playDirection: "発言順：",
    directionForward: "時計回り \u2192",
    directionBackward: "\u2190 反時計回り",
    confirmCustomWords: "内容を確定",
    customWordsPrompt: "ゲームに参加しない人がお題を入力してください。",
    gamePhaseVoting: "話し合いと投票タイム",
    identityRevealed: "{player}は{role}でした！",
    handToPlayerN: "プレイヤー{n}にスマホを渡す"
  }
};
