const words_zh_CN = [
  { a: "苹果", b: "梨", aTranslation: "Apple", bTranslation: "Pear", aPronunciation: "píng guǒ", bPronunciation: "lí" },
  { a: "橘子", b: "柠檬", aTranslation: "Orange", bTranslation: "Lemon", aPronunciation: "jú zi", bPronunciation: "níng méng" },
  { a: "咖啡", b: "茶", aTranslation: "Coffee", bTranslation: "Tea", aPronunciation: "kā fēi", bPronunciation: "chá" },
  { a: "卡布奇诺", b: "拿铁", aTranslation: "Cappuccino", bTranslation: "Latte", aPronunciation: "kǎ bù qí nuò", bPronunciation: "ná tiě" },
  { a: "披萨", b: "汉堡包", aTranslation: "Pizza", bTranslation: "Hamburger", aPronunciation: "pī sà", bPronunciation: "hàn bǎo bāo" },
  { a: "面包", b: "米饭", aTranslation: "Bread", bTranslation: "Rice", aPronunciation: "miàn bāo", bPronunciation: "mǐ fàn" },
  { a: "牛奶", b: "果汁", aTranslation: "Milk", bTranslation: "Juice", aPronunciation: "niú nǎi", bPronunciation: "guǒ zhī" },
  { a: "黄油", b: "奶酪", aTranslation: "Butter", bTranslation: "Cheese", aPronunciation: "huáng yóu", bPronunciation: "nǎi lào" },
  { a: "冰淇淋", b: "蛋糕", aTranslation: "Ice Cream", bTranslation: "Cake", aPronunciation: "bīng qí lín", bPronunciation: "dàn gāo" },
  { a: "可乐", b: "雪碧", aTranslation: "Cola", bTranslation: "Sprite", aPronunciation: "kě lè", bPronunciation: "xuě bì" },
  { a: "西瓜", b: "哈密瓜", aTranslation: "Watermelon", bTranslation: "Melon", aPronunciation: "xī guā", bPronunciation: "hā mì guā" },
  { a: "草莓", b: "樱桃", aTranslation: "Strawberry", bTranslation: "Cherry", aPronunciation: "cǎo méi", bPronunciation: "yīng táo" },
  { a: "牛排", b: "猪排", aTranslation: "Steak", bTranslation: "Pork Chop", aPronunciation: "niú pái", bPronunciation: "zhū pái" },
  { a: "面条", b: "意大利面", aTranslation: "Noodles", bTranslation: "Pasta", aPronunciation: "miàn tiáo", bPronunciation: "yì dà lì miàn" },
  { a: "寿司", b: "生鱼片", aTranslation: "Sushi", bTranslation: "Sashimi", aPronunciation: "shòu sī", bPronunciation: "shēng yú piàn" },
  { a: "巧克力", b: "糖果", aTranslation: "Chocolate", bTranslation: "Candy", aPronunciation: "qiǎo kè lì", bPronunciation: "táng guǒ" },
  { a: "土豆", b: "红薯", aTranslation: "Potato", bTranslation: "Sweet Potato", aPronunciation: "tǔ dòu", bPronunciation: "hóng shǔ" },
  { a: "洋葱", b: "大蒜", aTranslation: "Onion", bTranslation: "Garlic", aPronunciation: "yáng cōng", bPronunciation: "dà suàn" },
  { a: "西红柿", b: "胡萝卜", aTranslation: "Tomato", bTranslation: "Carrot", aPronunciation: "xī hóng shì", bPronunciation: "hú luó bo" },
  { a: "汤", b: "炖菜", aTranslation: "Soup", bTranslation: "Stew", aPronunciation: "tāng", bPronunciation: "dùn cài" },
  { a: "老虎", b: "狮子", aTranslation: "Tiger", bTranslation: "Lion", aPronunciation: "lǎo hǔ", bPronunciation: "shī zi" },
  { a: "鲨鱼", b: "海豚", aTranslation: "Shark", bTranslation: "Dolphin", aPronunciation: "shā yú", bPronunciation: "hǎi tún" },
  { a: "猫头鹰", b: "老鹰", aTranslation: "Owl", bTranslation: "Eagle", aPronunciation: "māo tóu yīng", bPronunciation: "lǎo yīng" },
  { a: "老鼠", b: "田鼠", aTranslation: "Mouse", bTranslation: "Rat", aPronunciation: "lǎo shǔ", bPronunciation: "tián shǔ" },
  { a: "兔子", b: "仓鼠", aTranslation: "Rabbit", bTranslation: "Hamster", aPronunciation: "tù zi", bPronunciation: "cāng shǔ" },
  { a: "马", b: "驴", aTranslation: "Horse", bTranslation: "Donkey", aPronunciation: "mǎ", bPronunciation: "lǘ" },
  { a: "奶牛", b: "绵羊", aTranslation: "Cow", bTranslation: "Sheep", aPronunciation: "nǎi niú", bPronunciation: "mián yáng" },
  { a: "猪", b: "山羊", aTranslation: "Pig", bTranslation: "Goat", aPronunciation: "zhū", bPronunciation: "shān yáng" },
  { a: "企鹅", b: "海豹", aTranslation: "Penguin", bTranslation: "Seal", aPronunciation: "qǐ é", bPronunciation: "hǎi bào" },
  { a: "蝴蝶", b: "飞蛾", aTranslation: "Butterfly", bTranslation: "Moth", aPronunciation: "hú dié", bPronunciation: "fēi é" },
  { a: "蜜蜂", b: "黄蜂", aTranslation: "Bee", bTranslation: "Wasp", aPronunciation: "mì fēng", bPronunciation: "huáng fēng" },
  { a: "蜘蛛", b: "蚂蚁", aTranslation: "Spider", bTranslation: "Ant", aPronunciation: "zhī zhū", bPronunciation: "mǎ yǐ" },
  { a: "海龟", b: "乌龟", aTranslation: "Turtle", bTranslation: "Tortoise", aPronunciation: "hǎi guī", bPronunciation: "wū guī" },
  { a: "青蛙", b: "蟾蜍", aTranslation: "Frog", bTranslation: "Toad", aPronunciation: "qīng wā", bPronunciation: "chán chú" },
  { a: "猴子", b: "大猩猩", aTranslation: "Monkey", bTranslation: "Gorilla", aPronunciation: "hóu zi", bPronunciation: "dà xīng xīng" },
  { a: "熊", b: "熊猫", aTranslation: "Bear", bTranslation: "Panda", aPronunciation: "xióng", bPronunciation: "xióng māo" },
  { a: "狐狸", b: "狼", aTranslation: "Fox", bTranslation: "Wolf", aPronunciation: "hú lí", bPronunciation: "láng" },
  { a: "鸭子", b: "鹅", aTranslation: "Duck", bTranslation: "Goose", aPronunciation: "yā zi", bPronunciation: "é" },
  { a: "狗", b: "猫", aTranslation: "Dog", bTranslation: "Cat", aPronunciation: "gǒu", bPronunciation: "māo" },
  { a: "鲸鱼", b: "鲨鱼", aTranslation: "Whale", bTranslation: "Shark", aPronunciation: "jīng yú", bPronunciation: "shā yú" },
  { a: "自行车", b: "摩托车", aTranslation: "Bicycle", bTranslation: "Motorbike", aPronunciation: "zì xíng chē", bPronunciation: "mó tuō chē" },
  { a: "汽车", b: "卡车", aTranslation: "Car", bTranslation: "Truck", aPronunciation: "qì chē", bPronunciation: "kǎ chē" },
  { a: "公交车", b: "出租车", aTranslation: "Bus", bTranslation: "Taxi", aPronunciation: "gōng jiāo chē", bPronunciation: "chū zū chē" },
  { a: "火车", b: "地铁", aTranslation: "Train", bTranslation: "Subway", aPronunciation: "huǒ chē", bPronunciation: "dì tiě" },
  { a: "飞机", b: "直升机", aTranslation: "Airplane", bTranslation: "Helicopter", aPronunciation: "fēi jī", bPronunciation: "zhí shēng jī" },
  { a: "小船", b: "轮船", aTranslation: "Boat", bTranslation: "Ship", aPronunciation: "xiǎo chuán", bPronunciation: "lún chuán" },
  { a: "独木舟", b: "皮划艇", aTranslation: "Canoe", bTranslation: "Kayak", aPronunciation: "dú mù zhōu", bPronunciation: "pí huá tǐng" },
  { a: "滑板", b: "旱冰鞋", aTranslation: "Skateboard", bTranslation: "Rollerblades", aPronunciation: "huá bǎn", bPronunciation: "hàn bīng xié" },
  { a: "滑板车", b: "平衡车", aTranslation: "Scooter", bTranslation: "Hoverboard", aPronunciation: "huá bǎn chē", bPronunciation: "píng héng chē" },
  { a: "救护车", b: "消防车", aTranslation: "Ambulance", bTranslation: "Fire Truck", aPronunciation: "jiù hù chē", bPronunciation: "xiāo fáng chē" },
  { a: "椅子", b: "凳子", aTranslation: "Chair", bTranslation: "Stool", aPronunciation: "yǐ zi", bPronunciation: "dèng zi" },
  { a: "沙发", b: "扶手椅", aTranslation: "Sofa", bTranslation: "Armchair", aPronunciation: "shā fā", bPronunciation: "fú shǒu yǐ" },
  { a: "书桌", b: "桌子", aTranslation: "Desk", bTranslation: "Table", aPronunciation: "shū zhuō", bPronunciation: "zhuō zi" },
  { a: "床", b: "床垫", aTranslation: "Bed", bTranslation: "Mattress", aPronunciation: "chuáng", bPronunciation: "chuáng diàn" },
  { a: "衣柜", b: "壁橱", aTranslation: "Wardrobe", bTranslation: "Closet", aPronunciation: "yī guì", bPronunciation: "bì chú" },
  { a: "书", b: "杂志", aTranslation: "Book", bTranslation: "Magazine", aPronunciation: "shū", bPronunciation: "zá zhì" },
  { a: "笔记本", b: "日记本", aTranslation: "Notebook", bTranslation: "Diary", aPronunciation: "bǐ jì běn", bPronunciation: "rì jì běn" },
  { a: "钢笔", b: "铅笔", aTranslation: "Pen", bTranslation: "Pencil", aPronunciation: "gāng bǐ", bPronunciation: "qiān bǐ" },
  { a: "记号笔", b: "荧光笔", aTranslation: "Marker", bTranslation: "Highlighter", aPronunciation: "jì hào bǐ", bPronunciation: "yíng guāng bǐ" },
  { a: "杯子", b: "玻璃杯", aTranslation: "Cup", bTranslation: "Glass", aPronunciation: "bēi zi", bPronunciation: "bō lí bēi" },
  { a: "盘子", b: "碗", aTranslation: "Plate", bTranslation: "Bowl", aPronunciation: "pán zi", bPronunciation: "wǎn" },
  { a: "勺子", b: "叉子", aTranslation: "Spoon", bTranslation: "Fork", aPronunciation: "sháo zi", bPronunciation: "chā zi" },
  { a: "刀", b: "剑", aTranslation: "Knife", bTranslation: "Sword", aPronunciation: "dāo", bPronunciation: "jiàn" },
  { a: "钟表", b: "手表", aTranslation: "Clock", bTranslation: "Watch", aPronunciation: "zhōng biǎo", bPronunciation: "shǒu biǎo" },
  { a: "电视", b: "显示器", aTranslation: "Television", bTranslation: "Monitor", aPronunciation: "diàn shì", bPronunciation: "xiǎn shì qì" },
  { a: "笔记本电脑", b: "平板电脑", aTranslation: "Laptop", bTranslation: "Tablet", aPronunciation: "bǐ jì běn diàn nǎo", bPronunciation: "píng bǎn diàn nǎo" },
  { a: "智能手机", b: "电话", aTranslation: "Smartphone", bTranslation: "Telephone", aPronunciation: "zhì néng shǒu jī", bPronunciation: "diàn huà" },
  { a: "收音机", b: "扬声器", aTranslation: "Radio", bTranslation: "Speaker", aPronunciation: "shōu yīn jī", bPronunciation: "yáng shēng qì" },
  { a: "窗户", b: "门", aTranslation: "Window", bTranslation: "Door", aPronunciation: "chuāng hù", bPronunciation: "mén" },
  { a: "屋顶", b: "天花板", aTranslation: "Roof", bTranslation: "Ceiling", aPronunciation: "wū dǐng", bPronunciation: "tiān huā bǎn" },
  { a: "大衣", b: "夹克", aTranslation: "Coat", bTranslation: "Jacket", aPronunciation: "dà yī", bPronunciation: "jiá kè" },
  { a: "毛衣", b: "卫衣", aTranslation: "Sweater", bTranslation: "Hoodie", aPronunciation: "máo yī", bPronunciation: "wèi yī" },
  { a: "衬衫", b: "T恤", aTranslation: "Shirt", bTranslation: "T-shirt", aPronunciation: "chèn shān", bPronunciation: "T xù" },
  { a: "长裤", b: "牛仔裤", aTranslation: "Trousers", bTranslation: "Jeans", aPronunciation: "cháng kù", bPronunciation: "niú zǎi kù" },
  { a: "短裤", b: "裙子", aTranslation: "Shorts", bTranslation: "Skirt", aPronunciation: "duǎn kù", bPronunciation: "qún zi" },
  { a: "鞋子", b: "靴子", aTranslation: "Shoes", bTranslation: "Boots", aPronunciation: "xié zi", bPronunciation: "xuē zi" },
  { a: "运动鞋", b: "凉鞋", aTranslation: "Sneakers", bTranslation: "Sandals", aPronunciation: "yùn dòng xié", bPronunciation: "liáng xié" },
  { a: "袜子", b: "丝袜", aTranslation: "Socks", bTranslation: "Stockings", aPronunciation: "wà zi", bPronunciation: "sī wà" },
  { a: "帽子", b: "棒球帽", aTranslation: "Hat", bTranslation: "Cap", aPronunciation: "mào zi", bPronunciation: "bàng qiú mào" },
  { a: "手套", b: "连指手套", aTranslation: "Gloves", bTranslation: "Mittens", aPronunciation: "shǒu tào", bPronunciation: "lián zhǐ shǒu tào" },
  { a: "图书馆", b: "书店", aTranslation: "Library", bTranslation: "Bookstore", aPronunciation: "tú shū guǎn", bPronunciation: "shū diàn" },
  { a: "医院", b: "诊所", aTranslation: "Hospital", bTranslation: "Clinic", aPronunciation: "yī yuàn", bPronunciation: "zhěn suǒ" },
  { a: "学校", b: "大学", aTranslation: "School", bTranslation: "University", aPronunciation: "xué xiào", bPronunciation: "dà xué" },
  { a: "公园", b: "花园", aTranslation: "Park", bTranslation: "Garden", aPronunciation: "gōng yuán", bPronunciation: "huā yuán" },
  { a: "河", b: "湖", aTranslation: "River", bTranslation: "Lake", aPronunciation: "hé", bPronunciation: "hú" },
  { a: "海", b: "海洋", aTranslation: "Sea", bTranslation: "Ocean", aPronunciation: "hǎi", bPronunciation: "hǎi yáng" },
  { a: "山", b: "丘陵", aTranslation: "Mountain", bTranslation: "Hill", aPronunciation: "shān", bPronunciation: "qiū líng" },
  { a: "森林", b: "树林", aTranslation: "Forest", bTranslation: "Woods", aPronunciation: "sēn lín", bPronunciation: "shù lín" },
  { a: "岛屿", b: "半岛", aTranslation: "Island", bTranslation: "Peninsula", aPronunciation: "dǎo yǔ", bPronunciation: "bàn dǎo" },
  { a: "沙漠", b: "海滩", aTranslation: "Desert", bTranslation: "Beach", aPronunciation: "shā mò", bPronunciation: "hǎi tān" },
  { a: "医生", b: "护士", aTranslation: "Doctor", bTranslation: "Nurse", aPronunciation: "yī shēng", bPronunciation: "hù shì" },
  { a: "老师", b: "教授", aTranslation: "Teacher", bTranslation: "Professor", aPronunciation: "lǎo shī", bPronunciation: "jiào shòu" },
  { a: "警察", b: "侦探", aTranslation: "Police", bTranslation: "Detective", aPronunciation: "jǐng chá", bPronunciation: "zhēn tàn" },
  { a: "歌手", b: "演员", aTranslation: "Singer", bTranslation: "Actor", aPronunciation: "gē shǒu", bPronunciation: "yǎn yuán" },
  { a: "作家", b: "记者", aTranslation: "Writer", bTranslation: "Journalist", aPronunciation: "zuò jiā", bPronunciation: "jì zhě" },
  { a: "厨师", b: "面包师", aTranslation: "Chef", bTranslation: "Baker", aPronunciation: "chú shī", bPronunciation: "miàn bāo shī" },
  { a: "飞行员", b: "船长", aTranslation: "Pilot", bTranslation: "Captain", aPronunciation: "fēi xíng yuán", bPronunciation: "chuán zhǎng" },
  { a: "学生", b: "小学生", aTranslation: "Student", bTranslation: "Pupil", aPronunciation: "xué shēng", bPronunciation: "xiǎo xué shēng" },
  { a: "国王", b: "皇帝", aTranslation: "King", bTranslation: "Emperor", aPronunciation: "guó wáng", bPronunciation: "huáng dì" },
  { a: "农民", b: "渔夫", aTranslation: "Farmer", bTranslation: "Fisherman", aPronunciation: "nóng mín", bPronunciation: "yú fū" },
  { a: "吉他", b: "小提琴", aTranslation: "Guitar", bTranslation: "Violin", aPronunciation: "jí tā", bPronunciation: "xiǎo tí qín" },
  { a: "钢琴", b: "电子琴", aTranslation: "Piano", bTranslation: "Keyboard", aPronunciation: "gāng qín", bPronunciation: "diàn zi qín" },
  { a: "长笛", b: "单簧管", aTranslation: "Flute", bTranslation: "Clarinet", aPronunciation: "cháng dí", bPronunciation: "dān huáng guǎn" },
  { a: "小号", b: "萨克斯", aTranslation: "Trumpet", bTranslation: "Saxophone", aPronunciation: "xiǎo hào", bPronunciation: "sà kè sī" },
  { a: "鼓", b: "铜钹", aTranslation: "Drum", bTranslation: "Cymbal", aPronunciation: "gǔ", bPronunciation: "tóng bó" },
  { a: "绘画", b: "素描", aTranslation: "Painting", bTranslation: "Drawing", aPronunciation: "huì huà", bPronunciation: "sù miáo" },
  { a: "雕塑", b: "雕像", aTranslation: "Sculpture", bTranslation: "Statue", aPronunciation: "diāo sù", bPronunciation: "diāo xiàng" },
  { a: "相片", b: "海报", aTranslation: "Photograph", bTranslation: "Poster", aPronunciation: "xiàng piān", bPronunciation: "hǎi bào" },
  { a: "博物馆", b: "画廊", aTranslation: "Museum", bTranslation: "Gallery", aPronunciation: "bó wù guǎn", bPronunciation: "huà láng" },
  { a: "电影", b: "话剧", aTranslation: "Movie", bTranslation: "Play", aPronunciation: "diàn yǐng", bPronunciation: "huà jù" },
  { a: "金", b: "银", aTranslation: "Gold", bTranslation: "Silver", aPronunciation: "jīn", bPronunciation: "yín" },
  { a: "钻石", b: "红宝石", aTranslation: "Diamond", bTranslation: "Ruby", aPronunciation: "zuàn shí", bPronunciation: "hóng bǎo shí" },
  { a: "雨", b: "雪", aTranslation: "Rain", bTranslation: "Snow", aPronunciation: "yǔ", bPronunciation: "xuě" },
  { a: "风", b: "风暴", aTranslation: "Wind", bTranslation: "Storm", aPronunciation: "fēng", bPronunciation: "fēng bào" },
  { a: "雷", b: "闪电", aTranslation: "Thunder", bTranslation: "Lightning", aPronunciation: "léi", bPronunciation: "shǎn diàn" },
  { a: "城市", b: "村庄", aTranslation: "City", bTranslation: "Village", aPronunciation: "chéng shì", bPronunciation: "cūn zhuāng" },
  { a: "街道", b: "小巷", aTranslation: "Street", bTranslation: "Alley", aPronunciation: "jiē dào", bPronunciation: "xiǎo xiàng" },
  { a: "桥", b: "隧道", aTranslation: "Bridge", bTranslation: "Tunnel", aPronunciation: "qiáo", bPronunciation: "suì dào" },
  { a: "房子", b: "公寓", aTranslation: "House", bTranslation: "Apartment", aPronunciation: "fáng zi", bPronunciation: "gōng yù" },
  { a: "城堡", b: "宫殿", aTranslation: "Castle", bTranslation: "Palace", aPronunciation: "chéng bǎo", bPronunciation: "gōng diàn" },
  { a: "酒店", b: "旅馆", aTranslation: "Hotel", bTranslation: "Inn", aPronunciation: "jiǔ diàn", bPronunciation: "lǚ guǎn" },
  { a: "餐厅", b: "咖啡馆", aTranslation: "Restaurant", bTranslation: "Cafe", aPronunciation: "cān tīng", bPronunciation: "kā fēi guǎn" },
  { a: "酒吧", b: "酒馆", aTranslation: "Bar", bTranslation: "Pub", aPronunciation: "jiǔ bā", bPronunciation: "jiǔ guǎn" },
  { a: "超市", b: "便利店", aTranslation: "Supermarket", bTranslation: "Convenience Store", aPronunciation: "chāo shì", bPronunciation: "biàn lì diàn" },
  { a: "百货公司", b: "购物中心", aTranslation: "Department Store", bTranslation: "Mall", aPronunciation: "bǎi huò gōng sī", bPronunciation: "gòu wù zhōng xīn" },
  { a: "演唱会", b: "音乐节", aTranslation: "Concert", bTranslation: "Festival", aPronunciation: "yǎn chàng huì", bPronunciation: "yīn yuè jié" },
  { a: "体育场", b: "竞技场", aTranslation: "Stadium", bTranslation: "Arena", aPronunciation: "tǐ yù chǎng", bPronunciation: "jìng jì chǎng" },
  { a: "健身房", b: "道场", aTranslation: "Gym", bTranslation: "Dojo", aPronunciation: "jiàn shēn fáng", bPronunciation: "dào chǎng" },
  { a: "游泳池", b: "温泉", aTranslation: "Pool", bTranslation: "Hot Spring", aPronunciation: "yóu yǒng chí", bPronunciation: "wēn quán" },
  { a: "数学", b: "科学", aTranslation: "Math", bTranslation: "Science", aPronunciation: "shù xué", bPronunciation: "kē xué" },
  { a: "历史", b: "地理", aTranslation: "History", bTranslation: "Geography", aPronunciation: "lì shǐ", bPronunciation: "dì lǐ" },
  { a: "物理", b: "化学", aTranslation: "Physics", bTranslation: "Chemistry", aPronunciation: "wù lǐ", bPronunciation: "huà xué" },
  { a: "生物学", b: "解剖学", aTranslation: "Biology", bTranslation: "Anatomy", aPronunciation: "shēng wù xué", bPronunciation: "jiě pōu xué" },
  { a: "美术", b: "音乐", aTranslation: "Art", bTranslation: "Music", aPronunciation: "měi shù", bPronunciation: "yīn yuè" },
  { a: "中提琴", b: "大提琴", aTranslation: "Viola", bTranslation: "Cello", aPronunciation: "zhōng tí qín", bPronunciation: "dà tí qín" },
  { a: "流行乐", b: "摇滚乐", aTranslation: "Pop", bTranslation: "Rock", aPronunciation: "liú xíng yuè", bPronunciation: "yáo gǔn yuè" },
  { a: "爵士乐", b: "蓝调", aTranslation: "Jazz", bTranslation: "Blues", aPronunciation: "jué shì yuè", bPronunciation: "lán diào" },
  { a: "古典乐", b: "歌剧", aTranslation: "Classical", bTranslation: "Opera", aPronunciation: "gǔ diǎn yuè", bPronunciation: "gē jù" },
  { a: "足球", b: "橄榄球", aTranslation: "Soccer", bTranslation: "Football", aPronunciation: "zú qiú", bPronunciation: "gǎn lǎn qiú" },
  { a: "篮球", b: "排球", aTranslation: "Basketball", bTranslation: "Volleyball", aPronunciation: "lán qiú", bPronunciation: "pái qiú" },
  { a: "棒球", b: "垒球", aTranslation: "Baseball", bTranslation: "Softball", aPronunciation: "bàng qiú", bPronunciation: "lěi qiú" },
  { a: "网球", b: "羽毛球", aTranslation: "Tennis", bTranslation: "Badminton", aPronunciation: "wǎng qiú", bPronunciation: "yǔ máo qiú" },
  { a: "乒乓球", b: "壁球", aTranslation: "Table Tennis", bTranslation: "Squash", aPronunciation: "pīng pāng qiú", bPronunciation: "bì qiú" },
  { a: "游泳", b: "跳水", aTranslation: "Swimming", bTranslation: "Diving", aPronunciation: "yóu yǒng", bPronunciation: "tiào shuǐ" },
  { a: "跑步", b: "慢跑", aTranslation: "Running", bTranslation: "Jogging", aPronunciation: "pǎo bù", bPronunciation: "màn pǎo" },
  { a: "滑雪", b: "单板滑雪", aTranslation: "Skiing", bTranslation: "Snowboarding", aPronunciation: "huá xuě", bPronunciation: "dān bǎn huá xuě" },
  { a: "滑冰", b: "冲浪", aTranslation: "Skating", bTranslation: "Surfing", aPronunciation: "huá bīng", bPronunciation: "chōng làng" },
  { a: "拳击", b: "摔跤", aTranslation: "Boxing", bTranslation: "Wrestling", aPronunciation: "quán jī", bPronunciation: "shuāi jiāo" },
  { a: "空手道", b: "柔道", aTranslation: "Karate", bTranslation: "Judo", aPronunciation: "kōng shǒu dào", bPronunciation: "róu dào" },
  { a: "长矛", b: "盾牌", aTranslation: "Spear", bTranslation: "Shield", aPronunciation: "cháng máo", bPronunciation: "dùn pái" },
  { a: "弓", b: "箭", aTranslation: "Bow", bTranslation: "Arrow", aPronunciation: "gōng", bPronunciation: "jiàn" },
  { a: "枪", b: "步枪", aTranslation: "Gun", bTranslation: "Rifle", aPronunciation: "qiāng", bPronunciation: "bù qiāng" },
  { a: "国际象棋", b: "围棋", aTranslation: "Chess", bTranslation: "Go", aPronunciation: "guó jì xiàng qí", bPronunciation: "wéi qí" },
  { a: "扑克牌", b: "麻将", aTranslation: "Cards", bTranslation: "Mahjong", aPronunciation: "pū kè pái", bPronunciation: "má jiàng" },
  { a: "拼图", b: "谜语", aTranslation: "Puzzle", bTranslation: "Riddle", aPronunciation: "pīn tú", bPronunciation: "mí yǔ" },
  { a: "机器人", b: "生化人", aTranslation: "Robot", bTranslation: "Cyborg", aPronunciation: "jī qì rén", bPronunciation: "shēng huà rén" },
  { a: "外星人", b: "怪物", aTranslation: "Alien", bTranslation: "Monster", aPronunciation: "wài xīng rén", bPronunciation: "guài wù" },
  { a: "幽灵", b: "丧尸", aTranslation: "Ghost", bTranslation: "Zombie", aPronunciation: "yōu líng", bPronunciation: "sàng shī" },
  { a: "吸血鬼", b: "狼人", aTranslation: "Vampire", bTranslation: "Werewolf", aPronunciation: "xī xuě guǐ", bPronunciation: "láng rén" },
  { a: "龙", b: "恐龙", aTranslation: "Dragon", bTranslation: "Dinosaur", aPronunciation: "lóng", bPronunciation: "kǒng lóng" },
  { a: "魔法", b: "科学", aTranslation: "Magic", bTranslation: "Science", aPronunciation: "mó fǎ", bPronunciation: "kē xué" },
  { a: "梦", b: "噩梦", aTranslation: "Dream", bTranslation: "Nightmare", aPronunciation: "mèng", bPronunciation: "è mèng" },
  { a: "微笑", b: "大笑", aTranslation: "Smile", bTranslation: "Laugh", aPronunciation: "wēi xiào", bPronunciation: "dà xiào" },
  { a: "眼泪", b: "哭泣", aTranslation: "Tear", bTranslation: "Crying", aPronunciation: "yǎn lèi", bPronunciation: "kū qì" },
  { a: "眼睛", b: "耳朵", aTranslation: "Eye", bTranslation: "Ear", aPronunciation: "yǎn jīng", bPronunciation: "ěr duǒ" },
  { a: "鼻子", b: "嘴巴", aTranslation: "Nose", bTranslation: "Mouth", aPronunciation: "bí zi", bPronunciation: "zuǐ bā" },
  { a: "手", b: "脚", aTranslation: "Hand", bTranslation: "Foot", aPronunciation: "shǒu", bPronunciation: "jiǎo" },
  { a: "手指", b: "脚趾", aTranslation: "Finger", bTranslation: "Toe", aPronunciation: "shǒu zhǐ", bPronunciation: "jiǎo zhǐ" },
  { a: "心脏", b: "大脑", aTranslation: "Heart", bTranslation: "Brain", aPronunciation: "xīn zàng", bPronunciation: "dà nǎo" },
  { a: "血液", b: "汗水", aTranslation: "Blood", bTranslation: "Sweat", aPronunciation: "xuě yè", bPronunciation: "hàn shuǐ" },
  { a: "春天", b: "秋天", aTranslation: "Spring", bTranslation: "Autumn", aPronunciation: "chūn tiān", bPronunciation: "qiū tiān" },
  { a: "夏天", b: "冬天", aTranslation: "Summer", bTranslation: "Winter", aPronunciation: "xià tiān", bPronunciation: "dōng tiān" },
  { a: "早上", b: "晚上", aTranslation: "Morning", bTranslation: "Night", aPronunciation: "zǎo shang", bPronunciation: "wǎn shang" },
  { a: "白天", b: "傍晚", aTranslation: "Day", bTranslation: "Evening", aPronunciation: "bái tiān", bPronunciation: "bàng wǎn" },
  { a: "星期一", b: "星期五", aTranslation: "Monday", bTranslation: "Friday", aPronunciation: "xīng qī yī", bPronunciation: "xīng qī wǔ" },
  { a: "一月", b: "十二月", aTranslation: "January", bTranslation: "December", aPronunciation: "yī yuè", bPronunciation: "shí èr yuè" },
  { a: "红色", b: "蓝色", aTranslation: "Red", bTranslation: "Blue", aPronunciation: "hóng sè", bPronunciation: "lán sè" },
  { a: "绿色", b: "黄色", aTranslation: "Green", bTranslation: "Yellow", aPronunciation: "lǜ sè", bPronunciation: "huáng sè" },
  { a: "黑色", b: "白色", aTranslation: "Black", bTranslation: "White", aPronunciation: "hēi sè", bPronunciation: "bái sè" },
  { a: "圆形", b: "方形", aTranslation: "Circle", bTranslation: "Square", aPronunciation: "yuán xíng", bPronunciation: "fāng xíng" },
  { a: "三角形", b: "长方形", aTranslation: "Triangle", bTranslation: "Rectangle", aPronunciation: "sān jiǎo xíng", bPronunciation: "cháng fāng xíng" },
  { a: "直线", b: "曲线", aTranslation: "Line", bTranslation: "Curve", aPronunciation: "zhí xiàn", bPronunciation: "qū xiàn" }
];
