const words_zh_TW = [
  { a: "蘋果", b: "梨", aTranslation: "Apple", bTranslation: "Pear", aPronunciation: "píng guǒ", bPronunciation: "lí" },
  { a: "橘子", b: "檸檬", aTranslation: "Orange", bTranslation: "Lemon", aPronunciation: "jú zi", bPronunciation: "níng méng" },
  { a: "咖啡", b: "茶", aTranslation: "Coffee", bTranslation: "Tea", aPronunciation: "kā fēi", bPronunciation: "chá" },
  { a: "卡布奇諾", b: "拿鐵", aTranslation: "Cappuccino", bTranslation: "Latte", aPronunciation: "kǎ bù qí nuò", bPronunciation: "ná tiě" },
  { a: "披薩", b: "漢堡", aTranslation: "Pizza", bTranslation: "Hamburger", aPronunciation: "pī sà", bPronunciation: "hàn bǎo" },
  { a: "麵包", b: "米飯", aTranslation: "Bread", bTranslation: "Rice", aPronunciation: "miàn bāo", bPronunciation: "mǐ fàn" },
  { a: "牛奶", b: "果汁", aTranslation: "Milk", bTranslation: "Juice", aPronunciation: "niú nǎi", bPronunciation: "guǒ zhī" },
  { a: "奶油", b: "起司", aTranslation: "Butter", bTranslation: "Cheese", aPronunciation: "nǎi yóu", bPronunciation: "qǐ sī" },
  { a: "冰淇淋", b: "蛋糕", aTranslation: "Ice Cream", bTranslation: "Cake", aPronunciation: "bīng qí lín", bPronunciation: "dàn gāo" },
  { a: "可樂", b: "雪碧", aTranslation: "Cola", bTranslation: "Sprite", aPronunciation: "kě lè", bPronunciation: "xuě bì" },
  { a: "西瓜", b: "哈密瓜", aTranslation: "Watermelon", bTranslation: "Melon", aPronunciation: "xī guā", bPronunciation: "hā mì guā" },
  { a: "草莓", b: "櫻桃", aTranslation: "Strawberry", bTranslation: "Cherry", aPronunciation: "cǎo méi", bPronunciation: "yīng táo" },
  { a: "牛排", b: "豬排", aTranslation: "Steak", bTranslation: "Pork Chop", aPronunciation: "niú pái", bPronunciation: "zhū pái" },
  { a: "麵條", b: "義大利麵", aTranslation: "Noodles", bTranslation: "Pasta", aPronunciation: "miàn tiáo", bPronunciation: "yì dà lì miàn" },
  { a: "壽司", b: "生魚片", aTranslation: "Sushi", bTranslation: "Sashimi", aPronunciation: "shòu sī", bPronunciation: "shēng yú piàn" },
  { a: "巧克力", b: "糖果", aTranslation: "Chocolate", bTranslation: "Candy", aPronunciation: "qiǎo kè lì", bPronunciation: "táng guǒ" },
  { a: "馬鈴薯", b: "地瓜", aTranslation: "Potato", bTranslation: "Sweet Potato", aPronunciation: "mǎ líng shǔ", bPronunciation: "dì guā" },
  { a: "洋蔥", b: "大蒜", aTranslation: "Onion", bTranslation: "Garlic", aPronunciation: "yáng cōng", bPronunciation: "dà suàn" },
  { a: "番茄", b: "胡蘿蔔", aTranslation: "Tomato", bTranslation: "Carrot", aPronunciation: "fān qié", bPronunciation: "hú luó bó" },
  { a: "湯", b: "燉菜", aTranslation: "Soup", bTranslation: "Stew", aPronunciation: "tāng", bPronunciation: "dùn cài" },
  { a: "老虎", b: "獅子", aTranslation: "Tiger", bTranslation: "Lion", aPronunciation: "lǎo hǔ", bPronunciation: "shī zi" },
  { a: "鯊魚", b: "海豚", aTranslation: "Shark", bTranslation: "Dolphin", aPronunciation: "shā yú", bPronunciation: "hǎi tún" },
  { a: "貓頭鷹", b: "老鷹", aTranslation: "Owl", bTranslation: "Eagle", aPronunciation: "māo tóu yīng", bPronunciation: "lǎo yīng" },
  { a: "老鼠", b: "田鼠", aTranslation: "Mouse", bTranslation: "Rat", aPronunciation: "lǎo shǔ", bPronunciation: "tián shǔ" },
  { a: "兔子", b: "倉鼠", aTranslation: "Rabbit", bTranslation: "Hamster", aPronunciation: "tù zi", bPronunciation: "cāng shǔ" },
  { a: "馬", b: "驢", aTranslation: "Horse", bTranslation: "Donkey", aPronunciation: "mǎ", bPronunciation: "lǘ" },
  { a: "乳牛", b: "綿羊", aTranslation: "Cow", bTranslation: "Sheep", aPronunciation: "rǔ niú", bPronunciation: "mián yáng" },
  { a: "豬", b: "山羊", aTranslation: "Pig", bTranslation: "Goat", aPronunciation: "zhū", bPronunciation: "shān yáng" },
  { a: "企鵝", b: "海豹", aTranslation: "Penguin", bTranslation: "Seal", aPronunciation: "qǐ é", bPronunciation: "hǎi bào" },
  { a: "蝴蝶", b: "飛蛾", aTranslation: "Butterfly", bTranslation: "Moth", aPronunciation: "hú dié", bPronunciation: "fēi é" },
  { a: "蜜蜂", b: "黃蜂", aTranslation: "Bee", bTranslation: "Wasp", aPronunciation: "mì fēng", bPronunciation: "huáng fēng" },
  { a: "蜘蛛", b: "螞蟻", aTranslation: "Spider", bTranslation: "Ant", aPronunciation: "zhī zhū", bPronunciation: "mǎ yǐ" },
  { a: "海龜", b: "烏龜", aTranslation: "Turtle", bTranslation: "Tortoise", aPronunciation: "hǎi guī", bPronunciation: "wū guī" },
  { a: "青蛙", b: "蟾蜍", aTranslation: "Frog", bTranslation: "Toad", aPronunciation: "qīng wā", bPronunciation: "chán chú" },
  { a: "猴子", b: "大猩猩", aTranslation: "Monkey", bTranslation: "Gorilla", aPronunciation: "hóu zi", bPronunciation: "dà xīng xīng" },
  { a: "熊", b: "熊貓", aTranslation: "Bear", bTranslation: "Panda", aPronunciation: "xióng", bPronunciation: "xióng māo" },
  { a: "狐狸", b: "狼", aTranslation: "Fox", bTranslation: "Wolf", aPronunciation: "hú lí", bPronunciation: "láng" },
  { a: "鴨子", b: "鵝", aTranslation: "Duck", bTranslation: "Goose", aPronunciation: "yā zi", bPronunciation: "é" },
  { a: "狗", b: "貓", aTranslation: "Dog", bTranslation: "Cat", aPronunciation: "gǒu", bPronunciation: "māo" },
  { a: "鯨魚", b: "鯊魚", aTranslation: "Whale", bTranslation: "Shark", aPronunciation: "jīng yú", bPronunciation: "shā yú" },
  { a: "自行車", b: "摩托車", aTranslation: "Bicycle", bTranslation: "Motorbike", aPronunciation: "zì xíng chē", bPronunciation: "mó tuō chē" },
  { a: "汽車", b: "卡車", aTranslation: "Car", bTranslation: "Truck", aPronunciation: "qì chē", bPronunciation: "kǎ chē" },
  { a: "公車", b: "計程車", aTranslation: "Bus", bTranslation: "Taxi", aPronunciation: "gōng chē", bPronunciation: "jì chéng chē" },
  { a: "火車", b: "捷運", aTranslation: "Train", bTranslation: "Subway", aPronunciation: "huǒ chē", bPronunciation: "jié yùn" },
  { a: "飛機", b: "直升機", aTranslation: "Airplane", bTranslation: "Helicopter", aPronunciation: "fēi jī", bPronunciation: "zhí shēng jī" },
  { a: "小船", b: "輪船", aTranslation: "Boat", bTranslation: "Ship", aPronunciation: "xiǎo chuán", bPronunciation: "lún chuán" },
  { a: "獨木舟", b: "皮划艇", aTranslation: "Canoe", bTranslation: "Kayak", aPronunciation: "dú mù zhōu", bPronunciation: "pí huá tǐng" },
  { a: "滑板", b: "直排輪", aTranslation: "Skateboard", bTranslation: "Rollerblades", aPronunciation: "huá bǎn", bPronunciation: "zhí pái lún" },
  { a: "滑板車", b: "平衡車", aTranslation: "Scooter", bTranslation: "Hoverboard", aPronunciation: "huá bǎn chē", bPronunciation: "píng héng chē" },
  { a: "救護車", b: "消防車", aTranslation: "Ambulance", bTranslation: "Fire Truck", aPronunciation: "jiù hù chē", bPronunciation: "xiāo fáng chē" },
  { a: "椅子", b: "凳子", aTranslation: "Chair", bTranslation: "Stool", aPronunciation: "yǐ zi", bPronunciation: "dèng zi" },
  { a: "沙發", b: "扶手椅", aTranslation: "Sofa", bTranslation: "Armchair", aPronunciation: "shā fā", bPronunciation: "fú shǒu yǐ" },
  { a: "書桌", b: "桌子", aTranslation: "Desk", bTranslation: "Table", aPronunciation: "shū zhuō", bPronunciation: "zhuō zi" },
  { a: "床", b: "床墊", aTranslation: "Bed", bTranslation: "Mattress", aPronunciation: "chuáng", bPronunciation: "chuáng diàn" },
  { a: "衣櫥", b: "壁櫥", aTranslation: "Wardrobe", bTranslation: "Closet", aPronunciation: "yī chú", bPronunciation: "bì chú" },
  { a: "書", b: "雜誌", aTranslation: "Book", bTranslation: "Magazine", aPronunciation: "shū", bPronunciation: "zá zhì" },
  { a: "筆記本", b: "日記本", aTranslation: "Notebook", bTranslation: "Diary", aPronunciation: "bǐ jì běn", bPronunciation: "rì jì běn" },
  { a: "鋼筆", b: "鉛筆", aTranslation: "Pen", bTranslation: "Pencil", aPronunciation: "gāng bǐ", bPronunciation: "qiān bǐ" },
  { a: "麥克筆", b: "螢光筆", aTranslation: "Marker", bTranslation: "Highlighter", aPronunciation: "mài kè bǐ", bPronunciation: "yíng guāng bǐ" },
  { a: "杯子", b: "玻璃杯", aTranslation: "Cup", bTranslation: "Glass", aPronunciation: "bēi zi", bPronunciation: "bō lí bēi" },
  { a: "盤子", b: "碗", aTranslation: "Plate", bTranslation: "Bowl", aPronunciation: "pán zi", bPronunciation: "wǎn" },
  { a: "湯匙", b: "叉子", aTranslation: "Spoon", bTranslation: "Fork", aPronunciation: "tāng shi", bPronunciation: "chā zi" },
  { a: "刀", b: "劍", aTranslation: "Knife", bTranslation: "Sword", aPronunciation: "dāo", bPronunciation: "jiàn" },
  { a: "時鐘", b: "手錶", aTranslation: "Clock", bTranslation: "Watch", aPronunciation: "shí zhōng", bPronunciation: "shǒu biǎo" },
  { a: "電視", b: "螢幕", aTranslation: "Television", bTranslation: "Monitor", aPronunciation: "diàn shì", bPronunciation: "yíng mù" },
  { a: "筆記型電腦", b: "平板電腦", aTranslation: "Laptop", bTranslation: "Tablet", aPronunciation: "bǐ jì xíng diàn nǎo", bPronunciation: "píng bǎn diàn nǎo" },
  { a: "智慧型手機", b: "電話", aTranslation: "Smartphone", bTranslation: "Telephone", aPronunciation: "zhì huì xíng shǒu jī", bPronunciation: "diàn huà" },
  { a: "耳機", b: "麥克風", aTranslation: "Earphones", bTranslation: "Microphone", aPronunciation: "ěr jī", bPronunciation: "mài kè fēng" },
  { a: "窗戶", b: "門", aTranslation: "Window", bTranslation: "Door", aPronunciation: "chuāng hù", bPronunciation: "mén" },
  { a: "屋頂", b: "天花板", aTranslation: "Roof", bTranslation: "Ceiling", aPronunciation: "wū dǐng", bPronunciation: "tiān huā bǎn" },
  { a: "大衣", b: "夾克", aTranslation: "Coat", bTranslation: "Jacket", aPronunciation: "dà yī", bPronunciation: "jiā kè" },
  { a: "毛衣", b: "帽T", aTranslation: "Sweater", bTranslation: "Hoodie", aPronunciation: "máo yī", bPronunciation: "mào T" },
  { a: "襯衫", b: "T恤", aTranslation: "Shirt", bTranslation: "T-shirt", aPronunciation: "chèn shān", bPronunciation: "T xù" },
  { a: "長褲", b: "牛仔褲", aTranslation: "Trousers", bTranslation: "Jeans", aPronunciation: "zhǎng kù", bPronunciation: "niú zǎi kù" },
  { a: "短褲", b: "裙子", aTranslation: "Shorts", bTranslation: "Skirt", aPronunciation: "duǎn kù", bPronunciation: "qún zi" },
  { a: "鞋子", b: "靴子", aTranslation: "Shoes", bTranslation: "Boots", aPronunciation: "xié zi", bPronunciation: "xuē zi" },
  { a: "運動鞋", b: "涼鞋", aTranslation: "Sneakers", bTranslation: "Sandals", aPronunciation: "yùn dòng xié", bPronunciation: "liáng xié" },
  { a: "襪子", b: "絲襪", aTranslation: "Socks", bTranslation: "Stockings", aPronunciation: "wà zi", bPronunciation: "sī wà" },
  { a: "帽子", b: "鴨舌帽", aTranslation: "Hat", bTranslation: "Cap", aPronunciation: "mào zi", bPronunciation: "yā shé mào" },
  { a: "手套", b: "連指手套", aTranslation: "Gloves", bTranslation: "Mittens", aPronunciation: "shǒu tào", bPronunciation: "lián zhǐ shǒu tào" },
  { a: "圖書館", b: "書店", aTranslation: "Library", bTranslation: "Bookstore", aPronunciation: "tú shū guǎn", bPronunciation: "shū diàn" },
  { a: "醫院", b: "診所", aTranslation: "Hospital", bTranslation: "Clinic", aPronunciation: "yī yuàn", bPronunciation: "zhěn suǒ" },
  { a: "學校", b: "大學", aTranslation: "School", bTranslation: "University", aPronunciation: "xué xiào", bPronunciation: "dà xué" },
  { a: "公園", b: "花園", aTranslation: "Park", bTranslation: "Garden", aPronunciation: "gōng yuán", bPronunciation: "huā yuán" },
  { a: "河", b: "湖", aTranslation: "River", bTranslation: "Lake", aPronunciation: "hé", bPronunciation: "hú" },
  { a: "海", b: "海洋", aTranslation: "Sea", bTranslation: "Ocean", aPronunciation: "hǎi", bPronunciation: "hǎi yáng" },
  { a: "山", b: "丘陵", aTranslation: "Mountain", bTranslation: "Hill", aPronunciation: "shān", bPronunciation: "qiū líng" },
  { a: "森林", b: "樹林", aTranslation: "Forest", bTranslation: "Woods", aPronunciation: "sēn lín", bPronunciation: "shù lín" },
  { a: "島嶼", b: "半島", aTranslation: "Island", bTranslation: "Peninsula", aPronunciation: "dǎo yǔ", bPronunciation: "bàn dǎo" },
  { a: "沙漠", b: "海灘", aTranslation: "Desert", bTranslation: "Beach", aPronunciation: "shā mò", bPronunciation: "hǎi tān" },
  { a: "醫生", b: "護士", aTranslation: "Doctor", bTranslation: "Nurse", aPronunciation: "yī shēng", bPronunciation: "hù shì" },
  { a: "老師", b: "教授", aTranslation: "Teacher", bTranslation: "Professor", aPronunciation: "lǎo shī", bPronunciation: "jiào shòu" },
  { a: "警察", b: "偵探", aTranslation: "Police", bTranslation: "Detective", aPronunciation: "jǐng chá", bPronunciation: "zhēn tàn" },
  { a: "歌手", b: "演員", aTranslation: "Singer", bTranslation: "Actor", aPronunciation: "gē shǒu", bPronunciation: "yǎn yuán" },
  { a: "作家", b: "記者", aTranslation: "Writer", bTranslation: "Journalist", aPronunciation: "zuò jiā", bPronunciation: "jì zhě" },
  { a: "廚師", b: "麵包師", aTranslation: "Chef", bTranslation: "Baker", aPronunciation: "chú shī", bPronunciation: "miàn bāo shī" },
  { a: "飛行員", b: "船長", aTranslation: "Pilot", bTranslation: "Captain", aPronunciation: "fēi xíng yuán", bPronunciation: "chuán zhǎng" },
  { a: "學生", b: "小學生", aTranslation: "Student", bTranslation: "Pupil", aPronunciation: "xué shēng", bPronunciation: "xiǎo xué shēng" },
  { a: "國王", b: "皇帝", aTranslation: "King", bTranslation: "Emperor", aPronunciation: "guó wáng", bPronunciation: "huáng dì" },
  { a: "農民", b: "漁夫", aTranslation: "Farmer", bTranslation: "Fisherman", aPronunciation: "nóng mín", bPronunciation: "yú fū" },
  { a: "吉他", b: "小提琴", aTranslation: "Guitar", bTranslation: "Violin", aPronunciation: "jí tā", bPronunciation: "xiǎo tí qín" },
  { a: "鋼琴", b: "電子琴", aTranslation: "Piano", bTranslation: "Keyboard", aPronunciation: "gāng qín", bPronunciation: "diàn zi qín" },
  { a: "長笛", b: "單簧管", aTranslation: "Flute", bTranslation: "Clarinet", aPronunciation: "zhǎng dí", bPronunciation: "dān huáng guǎn" },
  { a: "小號", b: "薩克斯風", aTranslation: "Trumpet", bTranslation: "Saxophone", aPronunciation: "xiǎo hào", bPronunciation: "sà kè sī fēng" },
  { a: "鼓", b: "銅鈸", aTranslation: "Drum", bTranslation: "Cymbal", aPronunciation: "gǔ", bPronunciation: "tóng bó" },
  { a: "繪畫", b: "素描", aTranslation: "Painting", bTranslation: "Drawing", aPronunciation: "huì huà", bPronunciation: "sù miáo" },
  { a: "雕塑", b: "雕像", aTranslation: "Sculpture", bTranslation: "Statue", aPronunciation: "diāo sù", bPronunciation: "diāo xiàng" },
  { a: "照片", b: "海報", aTranslation: "Photograph", bTranslation: "Poster", aPronunciation: "zhào piān", bPronunciation: "hǎi bào" },
  { a: "博物館", b: "畫廊", aTranslation: "Museum", bTranslation: "Gallery", aPronunciation: "bó wù guǎn", bPronunciation: "huà láng" },
  { a: "電影", b: "舞台劇", aTranslation: "Movie", bTranslation: "Play", aPronunciation: "diàn yǐng", bPronunciation: "wǔ tái jù" },
  { a: "金", b: "銀", aTranslation: "Gold", bTranslation: "Silver", aPronunciation: "jīn", bPronunciation: "yín" },
  { a: "鑽石", b: "紅寶石", aTranslation: "Diamond", bTranslation: "Ruby", aPronunciation: "zuàn shí", bPronunciation: "hóng bǎo shí" },
  { a: "雨", b: "雪", aTranslation: "Rain", bTranslation: "Snow", aPronunciation: "yǔ", bPronunciation: "xuě" },
  { a: "風", b: "風暴", aTranslation: "Wind", bTranslation: "Storm", aPronunciation: "fēng", bPronunciation: "fēng bào" },
  { a: "雷", b: "閃電", aTranslation: "Thunder", bTranslation: "Lightning", aPronunciation: "léi", bPronunciation: "shǎn diàn" },
  { a: "城市", b: "村莊", aTranslation: "City", bTranslation: "Village", aPronunciation: "chéng shì", bPronunciation: "cūn zhuāng" },
  { a: "街道", b: "小巷", aTranslation: "Street", bTranslation: "Alley", aPronunciation: "jiē dào", bPronunciation: "xiǎo xiàng" },
  { a: "橋", b: "隧道", aTranslation: "Bridge", bTranslation: "Tunnel", aPronunciation: "qiáo", bPronunciation: "suì dào" },
  { a: "房子", b: "公寓", aTranslation: "House", bTranslation: "Apartment", aPronunciation: "fáng zi", bPronunciation: "gōng yù" },
  { a: "城堡", b: "宮殿", aTranslation: "Castle", bTranslation: "Palace", aPronunciation: "chéng bǎo", bPronunciation: "gōng diàn" },
  { a: "飯店", b: "旅館", aTranslation: "Hotel", bTranslation: "Inn", aPronunciation: "fàn diàn", bPronunciation: "lǚ guǎn" },
  { a: "餐廳", b: "咖啡館", aTranslation: "Restaurant", bTranslation: "Cafe", aPronunciation: "cān tīng", bPronunciation: "kā fēi guǎn" },
  { a: "酒吧", b: "酒館", aTranslation: "Bar", bTranslation: "Pub", aPronunciation: "jiǔ bā", bPronunciation: "jiǔ guǎn" },
  { a: "超市", b: "便利商店", aTranslation: "Supermarket", bTranslation: "Convenience Store", aPronunciation: "chāo shì", bPronunciation: "biàn lì shāng diàn" },
  { a: "百貨公司", b: "購物中心", aTranslation: "Department Store", bTranslation: "Mall", aPronunciation: "bǎi huò gōng sī", bPronunciation: "gòu wù zhōng xīn" },
  { a: "演唱會", b: "音樂節", aTranslation: "Concert", bTranslation: "Festival", aPronunciation: "yǎn chàng huì", bPronunciation: "yīn yuè jié" },
  { a: "體育場", b: "競技場", aTranslation: "Stadium", bTranslation: "Arena", aPronunciation: "tǐ yù chǎng", bPronunciation: "jìng jì chǎng" },
  { a: "健身房", b: "道場", aTranslation: "Gym", bTranslation: "Dojo", aPronunciation: "jiàn shēn fáng", bPronunciation: "dào chǎng" },
  { a: "游泳池", b: "溫泉", aTranslation: "Pool", bTranslation: "Hot Spring", aPronunciation: "yóu yǒng chí", bPronunciation: "wēn quán" },
  { a: "數學", b: "科學", aTranslation: "Math", bTranslation: "Science", aPronunciation: "shù xué", bPronunciation: "kē xué" },
  { a: "歷史", b: "地理", aTranslation: "History", bTranslation: "Geography", aPronunciation: "lì shǐ", bPronunciation: "dì lǐ" },
  { a: "物理", b: "化學", aTranslation: "Physics", bTranslation: "Chemistry", aPronunciation: "wù lǐ", bPronunciation: "huà xué" },
  { a: "生物學", b: "解剖學", aTranslation: "Biology", bTranslation: "Anatomy", aPronunciation: "shēng wù xué", bPronunciation: "jiě pōu xué" },
  { a: "美術", b: "音樂", aTranslation: "Art", bTranslation: "Music", aPronunciation: "měi shù", bPronunciation: "yīn yuè" },
  { a: "中提琴", b: "大提琴", aTranslation: "Viola", bTranslation: "Cello", aPronunciation: "zhōng tí qín", bPronunciation: "dà tí qín" },
  { a: "流行樂", b: "搖滾樂", aTranslation: "Pop", bTranslation: "Rock", aPronunciation: "liú xíng yuè", bPronunciation: "yáo gǔn yuè" },
  { a: "爵士樂", b: "藍調", aTranslation: "Jazz", bTranslation: "Blues", aPronunciation: "jué shì yuè", bPronunciation: "lán diào" },
  { a: "古典樂", b: "歌劇", aTranslation: "Classical", bTranslation: "Opera", aPronunciation: "gǔ diǎn yuè", bPronunciation: "gē jù" },
  { a: "足球", b: "橄欖球", aTranslation: "Soccer", bTranslation: "Football", aPronunciation: "zú qiú", bPronunciation: "gǎn lǎn qiú" },
  { a: "籃球", b: "排球", aTranslation: "Basketball", bTranslation: "Volleyball", aPronunciation: "lán qiú", bPronunciation: "pái qiú" },
  { a: "棒球", b: "壘球", aTranslation: "Baseball", bTranslation: "Softball", aPronunciation: "bàng qiú", bPronunciation: "lěi qiú" },
  { a: "網球", b: "羽毛球", aTranslation: "Tennis", bTranslation: "Badminton", aPronunciation: "wǎng qiú", bPronunciation: "yǔ máo qiú" },
  { a: "桌球", b: "壁球", aTranslation: "Table Tennis", bTranslation: "Squash", aPronunciation: "zhuō qiú", bPronunciation: "bì qiú" },
  { a: "游泳", b: "跳水", aTranslation: "Swimming", bTranslation: "Diving", aPronunciation: "yóu yǒng", bPronunciation: "tiào shuǐ" },
  { a: "跑步", b: "慢跑", aTranslation: "Running", bTranslation: "Jogging", aPronunciation: "pǎo bù", bPronunciation: "màn pǎo" },
  { a: "滑雪", b: "單板滑雪", aTranslation: "Skiing", bTranslation: "Snowboarding", aPronunciation: "huá xuě", bPronunciation: "dān bǎn huá xuě" },
  { a: "滑冰", b: "衝浪", aTranslation: "Skating", bTranslation: "Surfing", aPronunciation: "huá bīng", bPronunciation: "chōng làng" },
  { a: "拳擊", b: "摔跤", aTranslation: "Boxing", bTranslation: "Wrestling", aPronunciation: "quán jī", bPronunciation: "shuāi jiāo" },
  { a: "空手道", b: "柔道", aTranslation: "Karate", bTranslation: "Judo", aPronunciation: "kōng shǒu dào", bPronunciation: "róu dào" },
  { a: "長矛", b: "盾牌", aTranslation: "Spear", bTranslation: "Shield", aPronunciation: "cháng máo", bPronunciation: "dùn pái" },
  { a: "弓", b: "箭", aTranslation: "Bow", bTranslation: "Arrow", aPronunciation: "gōng", bPronunciation: "jiàn" },
  { a: "槍", b: "步槍", aTranslation: "Gun", bTranslation: "Rifle", aPronunciation: "qiāng", bPronunciation: "bù qiāng" },
  { a: "國際象棋", b: "圍棋", aTranslation: "Chess", bTranslation: "Go", aPronunciation: "guó jì xiàng qí", bPronunciation: "wéi qí" },
  { a: "撲克牌", b: "麻將", aTranslation: "Cards", bTranslation: "Mahjong", aPronunciation: "pū kè pái", bPronunciation: "má jiàng" },
  { a: "拼圖", b: "謎語", aTranslation: "Puzzle", bTranslation: "Riddle", aPronunciation: "pīn tú", bPronunciation: "mí yǔ" },
  { a: "機器人", b: "生化人", aTranslation: "Robot", bTranslation: "Cyborg", aPronunciation: "jī qì rén", bPronunciation: "shēng huà rén" },
  { a: "外星人", b: "怪物", aTranslation: "Alien", bTranslation: "Monster", aPronunciation: "wài xīng rén", bPronunciation: "guài wù" },
  { a: "幽靈", b: "喪屍", aTranslation: "Ghost", bTranslation: "Zombie", aPronunciation: "yōu líng", bPronunciation: "sàng shī" },
  { a: "吸血鬼", b: "狼人", aTranslation: "Vampire", bTranslation: "Werewolf", aPronunciation: "xī xuě guǐ", bPronunciation: "láng rén" },
  { a: "龍", b: "恐龍", aTranslation: "Dragon", bTranslation: "Dinosaur", aPronunciation: "lóng", bPronunciation: "kǒng lóng" },
  { a: "魔法", b: "科學", aTranslation: "Magic", bTranslation: "Science", aPronunciation: "mó fǎ", bPronunciation: "kē xué" },
  { a: "夢", b: "噩夢", aTranslation: "Dream", bTranslation: "Nightmare", aPronunciation: "mèng", bPronunciation: "è mèng" },
  { a: "微笑", b: "大笑", aTranslation: "Smile", bTranslation: "Laugh", aPronunciation: "wēi xiào", bPronunciation: "dà xiào" },
  { a: "眼淚", b: "哭泣", aTranslation: "Tear", bTranslation: "Crying", aPronunciation: "yǎn lèi", bPronunciation: "kū qì" },
  { a: "眼睛", b: "耳朵", aTranslation: "Eye", bTranslation: "Ear", aPronunciation: "yǎn jīng", bPronunciation: "ěr duǒ" },
  { a: "鼻子", b: "嘴巴", aTranslation: "Nose", bTranslation: "Mouth", aPronunciation: "bí zi", bPronunciation: "zuǐ bā" },
  { a: "手", b: "腳", aTranslation: "Hand", bTranslation: "Foot", aPronunciation: "shǒu", bPronunciation: "jiǎo" },
  { a: "手指", b: "腳趾", aTranslation: "Finger", bTranslation: "Toe", aPronunciation: "shǒu zhǐ", bPronunciation: "jiǎo zhǐ" },
  { a: "心臟", b: "大腦", aTranslation: "Heart", bTranslation: "Brain", aPronunciation: "xīn zàng", bPronunciation: "dà nǎo" },
  { a: "血液", b: "汗水", aTranslation: "Blood", bTranslation: "Sweat", aPronunciation: "xuě yè", bPronunciation: "hàn shuǐ" },
  { a: "春天", b: "秋天", aTranslation: "Spring", bTranslation: "Autumn", aPronunciation: "chūn tiān", bPronunciation: "qiū tiān" },
  { a: "夏天", b: "冬天", aTranslation: "Summer", bTranslation: "Winter", aPronunciation: "xià tiān", bPronunciation: "dōng tiān" },
  { a: "早上", b: "晚上", aTranslation: "Morning", bTranslation: "Night", aPronunciation: "zǎo shang", bPronunciation: "wǎn shang" },
  { a: "白天", b: "傍晚", aTranslation: "Day", bTranslation: "Evening", aPronunciation: "bái tiān", bPronunciation: "bàng wǎn" },
  { a: "星期一", b: "星期五", aTranslation: "Monday", bTranslation: "Friday", aPronunciation: "xīng qī yī", bPronunciation: "xīng qī wǔ" },
  { a: "一月", b: "十二月", aTranslation: "January", bTranslation: "December", aPronunciation: "yī yuè", bPronunciation: "shí èr yuè" },
  { a: "紅色", b: "藍色", aTranslation: "Red", bTranslation: "Blue", aPronunciation: "hóng sè", bPronunciation: "lán sè" },
  { a: "綠色", b: "黃色", aTranslation: "Green", bTranslation: "Yellow", aPronunciation: "lǜ sè", bPronunciation: "huáng sè" },
  { a: "黑色", b: "白色", aTranslation: "Black", bTranslation: "White", aPronunciation: "hēi sè", bPronunciation: "bái sè" },
  { a: "圓形", b: "方形", aTranslation: "Circle", bTranslation: "Square", aPronunciation: "yuán xíng", bPronunciation: "fāng xíng" },
  { a: "三角形", b: "長方形", aTranslation: "Triangle", bTranslation: "Rectangle", aPronunciation: "sān jiǎo xíng", bPronunciation: "cháng fāng xíng" },
  { a: "直線", b: "曲線", aTranslation: "Line", bTranslation: "Curve", aPronunciation: "zhí xiàn", bPronunciation: "qū xiàn" },
  { a: "律師", b: "法官", aTranslation: "Lawyer", bTranslation: "Judge", aPronunciation: "lǜ shī", bPronunciation: "fǎ guān" },
  { a: "牙醫", b: "外科醫生", aTranslation: "Dentist", bTranslation: "Surgeon", aPronunciation: "yá yī", bPronunciation: "wài kē yī shēng" },
  { a: "水管工", b: "電工", aTranslation: "Plumber", bTranslation: "Electrician", aPronunciation: "shuǐ guǎn gōng", bPronunciation: "diàn gōng" },
  { a: "機械師", b: "木匠", aTranslation: "Mechanic", bTranslation: "Carpenter", aPronunciation: "jī xiè shī", bPronunciation: "mù jiàng" },
  { a: "消防員", b: "警官", aTranslation: "Firefighter", bTranslation: "Police Officer", aPronunciation: "xiāo fáng yuán", bPronunciation: "jǐng guān" },
  { a: "宇航員", b: "天文學家", aTranslation: "Astronaut", bTranslation: "Astronomer", aPronunciation: "yǔ háng yuán", bPronunciation: "tiān wén xué jiā" },
  { a: "魔術師", b: "小丑", aTranslation: "Magician", bTranslation: "Clown", aPronunciation: "mó shù shī", bPronunciation: "xiǎo chǒu" },
  { a: "理髮師", b: "美髮師", aTranslation: "Barber", bTranslation: "Hairdresser", aPronunciation: "lǐ fà shī", bPronunciation: "měi fà shī" },
  { a: "屠夫", b: "麵包師", aTranslation: "Butcher", bTranslation: "Baker", aPronunciation: "tú fū", bPronunciation: "miàn bāo shī" },
  { a: "裁縫", b: "鞋匠", aTranslation: "Tailor", bTranslation: "Cobbler", aPronunciation: "cái féng", bPronunciation: "xié jiàng" },
  { a: "摩天大樓", b: "塔", aTranslation: "Skyscraper", bTranslation: "Tower", aPronunciation: "mó tiān dà lóu", bPronunciation: "tǎ" },
  { a: "穀倉", b: "筒倉", aTranslation: "Barn", bTranslation: "Silo", aPronunciation: "gǔ cāng", bPronunciation: "tǒng cāng" },
  { a: "燈塔", b: "風車", aTranslation: "Lighthouse", bTranslation: "Windmill", aPronunciation: "dēng tǎ", bPronunciation: "fēng chē" },
  { a: "寺廟", b: "神社", aTranslation: "Temple", bTranslation: "Shrine", aPronunciation: "sì miào", bPronunciation: "shén shè" },
  { a: "教堂", b: "大教堂", aTranslation: "Church", bTranslation: "Cathedral", aPronunciation: "jiào táng", bPronunciation: "dà jiào táng" },
  { a: "金字塔", b: "獅身人面像", aTranslation: "Pyramid", bTranslation: "Sphinx", aPronunciation: "jīn zì tǎ", bPronunciation: "shī shēn rén miàn xiàng" },
  { a: "帳篷", b: "小木屋", aTranslation: "Tent", bTranslation: "Cabin", aPronunciation: "zhàng péng", bPronunciation: "xiǎo mù wū" },
  { a: "豪宅", b: "別墅", aTranslation: "Mansion", bTranslation: "Villa", aPronunciation: "háo zhái", bPronunciation: "bié shù" },
  { a: "銀行", b: "郵局", aTranslation: "Bank", bTranslation: "Post Office", aPronunciation: "yín háng", bPronunciation: "yóu jú" },
  { a: "藥店", b: "麵包店", aTranslation: "Pharmacy", bTranslation: "Bakery", aPronunciation: "yào diàn", bPronunciation: "miàn bāo diàn" },
  { a: "相機", b: "攝像機", aTranslation: "Camera", bTranslation: "Camcorder", aPronunciation: "xiàng jī", bPronunciation: "shè xiàng jī" },
  { a: "頭戴式耳機", b: "入耳式耳機", aTranslation: "Headphones", bTranslation: "Earbuds", aPronunciation: "tóu dài shì ěr jī", bPronunciation: "rù ěr shì ěr jī" },
  { a: "打印機", b: "掃描儀", aTranslation: "Printer", bTranslation: "Scanner", aPronunciation: "dǎ yìn jī", bPronunciation: "sǎo miáo yí" },
  { a: "鍵盤", b: "鼠標", aTranslation: "Keyboard", bTranslation: "Mouse", aPronunciation: "jiàn pán", bPronunciation: "shǔ biāo" },
  { a: "路由器", b: "調製解調器", aTranslation: "Router", bTranslation: "Modem", aPronunciation: "lù yóu qì", bPronunciation: "tiáo zhì jiě tiáo qì" },
  { a: "智能手錶", b: "健身追蹤器", aTranslation: "Smartwatch", bTranslation: "Fitness Tracker", aPronunciation: "zhì néng shǒu biǎo", bPronunciation: "jiàn shēn zhuī zōng qì" },
  { a: "無人機", b: "直升機", aTranslation: "Drone", bTranslation: "Helicopter", aPronunciation: "wú rén jī", bPronunciation: "zhí shēng jī" },
  { a: "電池", b: "充電器", aTranslation: "Battery", bTranslation: "Charger", aPronunciation: "diàn chí", bPronunciation: "chōng diàn qì" },
  { a: "麥克風", b: "揚聲器", aTranslation: "Microphone", bTranslation: "Speaker", aPronunciation: "mài kè fēng", bPronunciation: "yáng shēng qì" },
  { a: "投影儀", b: "屏幕", aTranslation: "Projector", bTranslation: "Screen", aPronunciation: "tóu yǐng yí", bPronunciation: "píng mù" },
  { a: "冰箱", b: "冷凍機", aTranslation: "Refrigerator", bTranslation: "Freezer", aPronunciation: "bīng xiāng", bPronunciation: "lěng dòng jī" },
  { a: "微波爐", b: "烤箱", aTranslation: "Microwave", bTranslation: "Oven", aPronunciation: "wēi bō lú", bPronunciation: "kǎo xiāng" },
  { a: "洗衣機", b: "烘乾機", aTranslation: "Washing Machine", bTranslation: "Dryer", aPronunciation: "xǐ yī jī", bPronunciation: "hōng gān jī" },
  { a: "洗碗機", b: "水槽", aTranslation: "Dishwasher", bTranslation: "Sink", aPronunciation: "xǐ wǎn jī", bPronunciation: "shuǐ cáo" },
  { a: "烤麵包機", b: "攪拌機", aTranslation: "Toaster", bTranslation: "Blender", aPronunciation: "kǎo miàn bāo jī", bPronunciation: "jiǎo bàn jī" },
  { a: "吸塵器", b: "掃帚", aTranslation: "Vacuum Cleaner", bTranslation: "Broom", aPronunciation: "xī chén qì", bPronunciation: "sào zhou" },
  { a: "風扇", b: "空調", aTranslation: "Fan", bTranslation: "Air Conditioner", aPronunciation: "fēng shàn", bPronunciation: "kōng tiáo" },
  { a: "檯燈", b: "燈籠", aTranslation: "Lamp", bTranslation: "Lantern", aPronunciation: "tái dēng", bPronunciation: "dēng lóng" },
  { a: "鏡子", b: "窗戶", aTranslation: "Mirror", bTranslation: "Window", aPronunciation: "jìng zi", bPronunciation: "chuāng hù" },
  { a: "地毯", b: "小地毯", aTranslation: "Carpet", bTranslation: "Rug", aPronunciation: "dì tǎn", bPronunciation: "xiǎo dì tǎn" },
  { a: "錢包", b: "手提包", aTranslation: "Wallet", bTranslation: "Purse", aPronunciation: "qián bāo", bPronunciation: "shǒu tí bāo" },
  { a: "背包", b: "手提箱", aTranslation: "Backpack", bTranslation: "Suitcase", aPronunciation: "bēi bāo", bPronunciation: "shǒu tí xiāng" },
  { a: "腰帶", b: "背帶", aTranslation: "Belt", bTranslation: "Suspenders", aPronunciation: "yāo dài", bPronunciation: "bēi dài" },
  { a: "領帶", b: "領結", aTranslation: "Tie", bTranslation: "Bowtie", aPronunciation: "lǐng dài", bPronunciation: "lǐng jié" },
  { a: "眼鏡", b: "隱形眼鏡", aTranslation: "Glasses", bTranslation: "Contact Lenses", aPronunciation: "yǎn jìng", bPronunciation: "yǐn xíng yǎn jìng" },
  { a: "太陽鏡", b: "護目鏡", aTranslation: "Sunglasses", bTranslation: "Goggles", aPronunciation: "tài yáng jìng", bPronunciation: "hù mù jìng" },
  { a: "頭盔", b: "帽子", aTranslation: "Helmet", bTranslation: "Hat", aPronunciation: "tóu kuī", bPronunciation: "mào zi" },
  { a: "戒指", b: "項鍊", aTranslation: "Ring", bTranslation: "Necklace", aPronunciation: "jiè zhǐ", bPronunciation: "xiàng liàn" },
  { a: "手鐲", b: "手錶", aTranslation: "Bracelet", bTranslation: "Watch", aPronunciation: "shǒu zhuó", bPronunciation: "shǒu biǎo" },
  { a: "耳環", b: "耳釘", aTranslation: "Piercing", bTranslation: "Earrings", aPronunciation: "ěr huán", bPronunciation: "ěr dīng" },
  { a: "拖拉機", b: "推土機", aTranslation: "Tractor", bTranslation: "Bulldozer", aPronunciation: "tuō lā jī", bPronunciation: "tuī tǔ jī" },
  { a: "起重機", b: "叉車", aTranslation: "Crane", bTranslation: "Forklift", aPronunciation: "qǐ zhòng jī", bPronunciation: "chā chē" },
  { a: "潛水艇", b: "魚雷", aTranslation: "Submarine", bTranslation: "Torpedo", aPronunciation: "qián shuǐ tǐng", bPronunciation: "yú léi" },
  { a: "熱氣球", b: "飛艇", aTranslation: "Hot Air Balloon", bTranslation: "Blimp", aPronunciation: "rè qì qiú", bPronunciation: "fēi tǐng" },
  { a: "宇宙飛船", b: "火箭", aTranslation: "Spaceship", bTranslation: "Rocket", aPronunciation: "yǔ zhòu fēi chuán", bPronunciation: "huǒ jiàn" },
  { a: "獨輪車", b: "三輪車", aTranslation: "Unicycle", bTranslation: "Tricycle", aPronunciation: "dú lún chē", bPronunciation: "sān lún chē" },
  { a: "輪椅", b: "嬰兒車", aTranslation: "Wheelchair", bTranslation: "Stroller", aPronunciation: "lún yǐ", bPronunciation: "yīng ér chē" },
  { a: "雪橇", b: "雪地摩托", aTranslation: "Sled", bTranslation: "Snowmobile", aPronunciation: "xuě qiāo", bPronunciation: "xuě dì mó tuō" },
  { a: "馬車", b: "四輪馬車", aTranslation: "Carriage", bTranslation: "Wagon", aPronunciation: "mǎ chē", bPronunciation: "sì lún mǎ chē" },
  { a: "遊艇", b: "帆船", aTranslation: "Yacht", bTranslation: "Sailboat", aPronunciation: "yóu tǐng", bPronunciation: "fān chuán" },
  { a: "大象", b: "犀牛", aTranslation: "Elephant", bTranslation: "Rhino", aPronunciation: "dà xiàng", bPronunciation: "xī niú" },
  { a: "長頸鹿", b: "斑馬", aTranslation: "Giraffe", bTranslation: "Zebra", aPronunciation: "cháng jǐng lù", bPronunciation: "bān mǎ" },
  { a: "袋鼠", b: "考拉", aTranslation: "Kangaroo", bTranslation: "Koala", aPronunciation: "dài shǔ", bPronunciation: "kǎo lā" },
  { a: "河馬", b: "鱷魚", aTranslation: "Hippopotamus", bTranslation: "Crocodile", aPronunciation: "hé mǎ", bPronunciation: "è yú" },
  { a: "駱駝", b: "羊駝", aTranslation: "Camel", bTranslation: "Alpaca", aPronunciation: "luò tuó", bPronunciation: "yáng tuó" },
  { a: "獵豹", b: "豹", aTranslation: "Cheetah", bTranslation: "Leopard", aPronunciation: "liè bào", bPronunciation: "bào" },
  { a: "孔雀", b: "鴕鳥", aTranslation: "Peacock", bTranslation: "Ostrich", aPronunciation: "kǒng què", bPronunciation: "tuó niǎo" },
  { a: "火烈鳥", b: "天鵝", aTranslation: "Flamingo", bTranslation: "Swan", aPronunciation: "huǒ liè niǎo", bPronunciation: "tiān é" },
  { a: "鸚鵡", b: "金絲雀", aTranslation: "Parrot", bTranslation: "Canary", aPronunciation: "yīng wǔ", bPronunciation: "jīn sī què" },
  { a: "啄木鳥", b: "鴿子", aTranslation: "Woodpecker", bTranslation: "Pigeon", aPronunciation: "zhuó mù niǎo", bPronunciation: "gē zi" },
  { a: "香蕉", b: "芭蕉", aTranslation: "Banana", bTranslation: "Plantain", aPronunciation: "xiāng jiāo", bPronunciation: "bā jiāo" },
  { a: "葡萄", b: "葡萄乾", aTranslation: "Grapes", bTranslation: "Raisins", aPronunciation: "pú tao", bPronunciation: "pú tao gān" },
  { a: "藍莓", b: "樹莓", aTranslation: "Blueberry", bTranslation: "Raspberry", aPronunciation: "lán méi", bPronunciation: "shù méi" },
  { a: "牛油果", b: "番石榴", aTranslation: "Avocado", bTranslation: "Guava", aPronunciation: "niú yóu guǒ", bPronunciation: "fān shí liú" },
  { a: "菠蘿", b: "椰子", aTranslation: "Pineapple", bTranslation: "Coconut", aPronunciation: "bō luó", bPronunciation: "yē zi" },
  { a: "西蘭花", b: "花椰菜", aTranslation: "Broccoli", bTranslation: "Cauliflower", aPronunciation: "xī lán huā", bPronunciation: "huā yē cài" },
  { a: "捲心菜", b: "生菜", aTranslation: "Cabbage", bTranslation: "Lettuce", aPronunciation: "juǎn xīn cài", bPronunciation: "shēng cài" },
  { a: "菠菜", b: "羽衣甘藍", aTranslation: "Spinach", bTranslation: "Kale", aPronunciation: "bō cài", bPronunciation: "yǔ yī gān lán" },
  { a: "黃瓜", b: "西葫蘆", aTranslation: "Cucumber", bTranslation: "Zucchini", aPronunciation: "huáng guā", bPronunciation: "xī hú lu" },
  { a: "蘑菇", b: "松露", aTranslation: "Mushroom", bTranslation: "Truffle", aPronunciation: "mó gu", bPronunciation: "sōng lù" },
  { a: "煎餅", b: "華夫餅", aTranslation: "Pancake", bTranslation: "Waffle", aPronunciation: "jiān bǐng", bPronunciation: "huá fū bǐng" },
  { a: "培根", b: "香腸", aTranslation: "Bacon", bTranslation: "Sausage", aPronunciation: "péi gēn", bPronunciation: "xiāng cháng" },
  { a: "墨西哥捲餅", b: "塔可", aTranslation: "Burrito", bTranslation: "Taco", aPronunciation: "mò xī gē juǎn bǐng", bPronunciation: "tǎ kě" },
  { a: "餃子", b: "春卷", aTranslation: "Dumpling", bTranslation: "Spring Roll", aPronunciation: "jiǎo zi", bPronunciation: "chūn juǎn" },
  { a: "咖喱", b: "燉菜", aTranslation: "Curry", bTranslation: "Stew", aPronunciation: "gā lí", bPronunciation: "dùn cài" },
  { a: "沙拉", b: "三明治", aTranslation: "Salad", bTranslation: "Sandwich", aPronunciation: "shā lā", bPronunciation: "sān míng zhì" },
  { a: "熱狗", b: "漢堡", aTranslation: "Hot Dog", bTranslation: "Burger", aPronunciation: "rè gǒu", bPronunciation: "hàn bǎo" },
  { a: "爆米花", b: "薯片", aTranslation: "Popcorn", bTranslation: "Chips", aPronunciation: "bào mǐ huā", bPronunciation: "shǔ piàn" },
  { a: "餅乾", b: "曲奇", aTranslation: "Biscuit", bTranslation: "Cookie", aPronunciation: "bǐng gān", bPronunciation: "qǔ qí" },
  { a: "甜甜圈", b: "百吉餅", aTranslation: "Donut", bTranslation: "Bagel", aPronunciation: "tián tián quān", bPronunciation: "bǎi jí bǐng" },
  { a: "島嶼", b: "礁石", aTranslation: "Island", bTranslation: "Reef", aPronunciation: "dǎo yǔ", bPronunciation: "jiāo shí" },
  { a: "懸崖", b: "峽谷", aTranslation: "Cliff", bTranslation: "Canyon", aPronunciation: "xuán yá", bPronunciation: "xiá gǔ" },
  { a: "洞穴", b: "石窟", aTranslation: "Cave", bTranslation: "Grotto", aPronunciation: "dòng xué", bPronunciation: "shí kū" },
  { a: "沼澤", b: "濕地", aTranslation: "Swamp", bTranslation: "Marsh", aPronunciation: "zhǎo zé", bPronunciation: "shī dì" },
  { a: "火山", b: "火山口", aTranslation: "Volcano", bTranslation: "Crater", aPronunciation: "huǒ shān", bPronunciation: "huǒ shān kǒu" },
  { a: "彗星", b: "小行星", aTranslation: "Comet", bTranslation: "Asteroid", aPronunciation: "huì xīng", bPronunciation: "xiǎo xíng xīng" },
  { a: "星系", b: "宇宙", aTranslation: "Galaxy", bTranslation: "Universe", aPronunciation: "xīng xì", bPronunciation: "yǔ zhòu" },
  { a: "行星", b: "恆星", aTranslation: "Planet", bTranslation: "Star", aPronunciation: "xíng xīng", bPronunciation: "héng xīng" },
  { a: "太陽", b: "月亮", aTranslation: "Sun", bTranslation: "Moon", aPronunciation: "tài yáng", bPronunciation: "yuè liang" },
  { a: "影子", b: "倒影", aTranslation: "Shadow", bTranslation: "Reflection", aPronunciation: "yǐng zi", bPronunciation: "dào yǐng" },
  { a: "義大利麵", b: "寬麵", aTranslation: "Spaghetti", bTranslation: "Fettuccine", aPronunciation: "yì dà lì miàn", bPronunciation: "kuān miàn" },
  { a: "千層麵", b: "義大利餃", aTranslation: "Lasagna", bTranslation: "Ravioli", aPronunciation: "qiān céng miàn", bPronunciation: "yì dà lì jiǎo" },
  { a: "粉絲", b: "米粉", aTranslation: "Glass Noodles", bTranslation: "Rice Vermicelli", aPronunciation: "fěn sī", bPronunciation: "mǐ fěn" },
  { a: "豆腐", b: "素肉", aTranslation: "Tofu", bTranslation: "Seitan", aPronunciation: "dòu fǔ", bPronunciation: "sù ròu" },
  { a: "芥末", b: "辣根", aTranslation: "Wasabi", bTranslation: "Horseradish", aPronunciation: "jiè mò", bPronunciation: "là gēn" },
  { a: "生薑", b: "姜黃", aTranslation: "Ginger", bTranslation: "Turmeric", aPronunciation: "shēng jiāng", bPronunciation: "jiāng huáng" },
  { a: "肉桂", b: "肉豆蔻", aTranslation: "Cinnamon", bTranslation: "Nutmeg", aPronunciation: "ròu guì", bPronunciation: "ròu dòu kòu" },
  { a: "香草", b: "焦糖", aTranslation: "Vanilla", bTranslation: "Caramel", aPronunciation: "xiāng cǎo", bPronunciation: "jiāo táng" },
  { a: "蜂蜜", b: "糖漿", aTranslation: "Honey", bTranslation: "Syrup", aPronunciation: "fēng mì", bPronunciation: "táng jiāng" },
  { a: "果醬", b: "橘子醬", aTranslation: "Jam", bTranslation: "Marmalade", aPronunciation: "guǒ jiàng", bPronunciation: "jú zi jiàng" },
  { a: "奶油", b: "人造奶油", aTranslation: "Butter", bTranslation: "Margarine", aPronunciation: "nǎi yóu", bPronunciation: "rén zào nǎi yóu" },
  { a: "優格", b: "開菲爾", aTranslation: "Yogurt", bTranslation: "Kefir", aPronunciation: "yōu gé", bPronunciation: "kāi fēi ěr" },
  { a: "美乃滋", b: "芥末醬", aTranslation: "Mayonnaise", bTranslation: "Mustard", aPronunciation: "měi nǎi zī", bPronunciation: "jiè mò jiàng" },
  { a: "番茄醬", b: "燒烤醬", aTranslation: "Ketchup", bTranslation: "BBQ Sauce", aPronunciation: "fān qié jiàng", bPronunciation: "shāo kǎo jiàng" },
  { a: "醋", b: "油", aTranslation: "Vinegar", bTranslation: "Oil", aPronunciation: "cù", bPronunciation: "yóu" },
  { a: "鹽", b: "胡椒", aTranslation: "Salt", bTranslation: "Pepper", aPronunciation: "yán", bPronunciation: "hú jiāo" },
  { a: "糖", b: "甜味劑", aTranslation: "Sugar", bTranslation: "Sweetener", aPronunciation: "táng", bPronunciation: "tián wèi jì" },
  { a: "麵粉", b: "澱粉", aTranslation: "Flour", bTranslation: "Starch", aPronunciation: "miàn fěn", bPronunciation: "diàn fěn" },
  { a: "泡打粉", b: "蘇打粉", aTranslation: "Baking Powder", bTranslation: "Baking Soda", aPronunciation: "pào dǎ fěn", bPronunciation: "sū dǎ fěn" },
  { a: "酵母", b: "酸種", aTranslation: "Yeast", bTranslation: "Sourdough Starter", aPronunciation: "jiào mǔ", bPronunciation: "suān zhǒng" },
  { a: "橡木", b: "楓木", aTranslation: "Oak", bTranslation: "Maple", aPronunciation: "xiàng mù", bPronunciation: "fēng mù" },
  { a: "松樹", b: "杉樹", aTranslation: "Pine", bTranslation: "Cedar", aPronunciation: "sōng shù", bPronunciation: "shān shù" },
  { a: "白樺", b: "柳樹", aTranslation: "Birch", bTranslation: "Willow", aPronunciation: "bái huà", bPronunciation: "liǔ shù" },
  { a: "竹子", b: "甘蔗", aTranslation: "Bamboo", bTranslation: "Sugar Cane", aPronunciation: "zhú zi", bPronunciation: "gān zhè" },
  { a: "仙人掌", b: "蘆薈", aTranslation: "Cactus", bTranslation: "Aloe", aPronunciation: "xiān rén zhǎng", bPronunciation: "lú huì" },
  { a: "玫瑰", b: "康乃馨", aTranslation: "Rose", bTranslation: "Carnation", aPronunciation: "méi guī", bPronunciation: "kāng nǎi xīn" },
  { a: "鬱金香", b: "水仙", aTranslation: "Tulip", bTranslation: "Daffodil", aPronunciation: "yù jīn xiāng", bPronunciation: "shuǐ xiān" },
  { a: "百合", b: "蘭花", aTranslation: "Lily", bTranslation: "Orchid", aPronunciation: "bǎi hé", bPronunciation: "蘭花" },
  { a: "雛菊", b: "向日葵", aTranslation: "Daisy", bTranslation: "Sunflower", aPronunciation: "chú jú", bPronunciation: "xiàng rì kuí" },
  { a: "薰衣草", b: "迷迭香", aTranslation: "Lavender", bTranslation: "Rosemary", aPronunciation: "xūn yī cǎo", bPronunciation: "mí dié xiāng" },
  { a: "薄荷", b: "羅勒", aTranslation: "Mint", bTranslation: "Basil", aPronunciation: "bò hé", bPronunciation: "luó lè" },
  { a: "百里香", b: "牛至", aTranslation: "Thyme", bTranslation: "Oregano", aPronunciation: "bǎi lǐ xiāng", bPronunciation: "niú zhì" },
  { a: "歐芹", b: "香菜", aTranslation: "Parsley", bTranslation: "Coriander", aPronunciation: "ōu qín", bPronunciation: "xiāng cài" },
  { a: "老鷹", b: "獵鷹", aTranslation: "Eagle", bTranslation: "Falcon", aPronunciation: "老鷹", bPronunciation: "獵鷹" },
  { a: "鷹", b: "禿鷲", aTranslation: "Hawk", bTranslation: "Vulture", aPronunciation: "yīng", bPronunciation: "tū jiù" },
  { a: "天鵝", b: "鵝", aTranslation: "Swan", bTranslation: "Goose", aPronunciation: "tiān é", bPronunciation: "é" },
  { a: "鴨子", b: "綠翅鴨", aTranslation: "Duck", bTranslation: "Teal", aPronunciation: "yā zi", bPronunciation: "lǜ chì yā" },
  { a: "鴿子", b: "斑鳩", aTranslation: "Pigeon", bTranslation: "Dove", aPronunciation: "gē zi", bPronunciation: "bān jiū" },
  { a: "貓頭鷹", b: "蝙蝠", aTranslation: "Owl", bTranslation: "Bat", aPronunciation: "māo tóu yīng", bPronunciation: "biān fú" },
  { a: "鸚鵡", b: "玄鳳鸚鵡", aTranslation: "Parrot", bTranslation: "Cockatiel", aPronunciation: "鸚鵡", bPronunciation: "玄鳳鸚鵡" },
  { a: "渡鴉", b: "烏鴉", aTranslation: "Raven", bTranslation: "Crow", aPronunciation: "dù yā", bPronunciation: "wū yā" },
  { a: "蜂鳥", b: "翠鳥", aTranslation: "Hummingbird", bTranslation: "Kingfisher", aPronunciation: "蜂鳥", bPronunciation: "翠鳥" },
  { a: "海鷗", b: "鵜鶘", aTranslation: "Seagull", bTranslation: "Pelican", aPronunciation: "海鷗", bPronunciation: "鵜鶘" },
  { a: "企鵝", b: "海鸚", aTranslation: "Penguin", bTranslation: "Puffin", aPronunciation: "企鵝", bPronunciation: "海鸚" },
  { a: "老虎", b: "豹", aTranslation: "Tiger", bTranslation: "Leopard", aPronunciation: "老虎", bPronunciation: "豹" },
  { a: "獅子", b: "獵豹", aTranslation: "Lion", bTranslation: "Cheetah", aPronunciation: "獅子", bPronunciation: "獵豹" },
  { a: "美洲豹", b: "黑豹", aTranslation: "Jaguar", bTranslation: "Panther", aPronunciation: "美洲豹", bPronunciation: "黑豹" },
  { a: "狼", b: "郊狼", aTranslation: "Wolf", bTranslation: "Coyote", aPronunciation: "láng", bPronunciation: "jiāo láng" },
  { a: "狐狸", b: "胡狼", aTranslation: "Fox", bTranslation: "Jackal", aPronunciation: "hú lí", bPronunciation: "hú láng" },
  { a: "鬣狗", b: "野狗", aTranslation: "Hyena", bTranslation: "Wild Dog", aPronunciation: "liè gǒu", bPronunciation: "yě gǒu" },
  { a: "熊", b: "灰熊", aTranslation: "Bear", bTranslation: "Grizzly", aPronunciation: "xióng", bPronunciation: "huī xióng" },
  { a: "浣熊", b: "果子狸", aTranslation: "Raccoon", bTranslation: "Civet", aPronunciation: "huàn xióng", bPronunciation: "果子狸" },
  { a: "臭鼬", b: "獾", aTranslation: "Skunk", bTranslation: "Badger", aPronunciation: "chòu yòu", bPronunciation: "huān" },
  { a: "水獺", b: "海狸", aTranslation: "Otter", bTranslation: "Beaver", aPronunciation: "shuǐ tǎ", bPronunciation: "hǎi lí" },
  { a: "松鼠", b: "花栗鼠", aTranslation: "Squirrel", bTranslation: "Chipmunk", aPronunciation: "松鼠", bPronunciation: "花栗鼠" },
  { a: "兔子", b: "野兔", aTranslation: "Rabbit", bTranslation: "Hare", aPronunciation: "兔子", bPronunciation: "野兔" },
  { a: "鹿", b: "麋鹿", aTranslation: "Deer", bTranslation: "Elk", aPronunciation: "lù", bPronunciation: "mí lù" },
  { a: "駝鹿", b: "馴鹿", aTranslation: "Moose", bTranslation: "Reindeer", aPronunciation: "tuó lù", bPronunciation: "xùn lù" },
  { a: "駱駝", b: "單峰駱駝", aTranslation: "Camel", bTranslation: "Dromedary", aPronunciation: "駱駝", bPronunciation: "單峰駱駝" },
  { a: "長頸鹿", b: "霍加狓", aTranslation: "Giraffe", bTranslation: "Okapi", aPronunciation: "長頸鹿", bPronunciation: "霍加狓" },
  { a: "大象", b: "猛獁象", aTranslation: "Elephant", bTranslation: "Mammoth", aPronunciation: "大象", bPronunciation: "猛獁象" },
  { a: "犀牛", b: "河馬", aTranslation: "Rhino", bTranslation: "Hippo", aPronunciation: "犀牛", bPronunciation: "河馬" },
  { a: "斑馬", b: "斑驢", aTranslation: "Zebra", bTranslation: "Quagga", aPronunciation: "斑馬", bPronunciation: "斑驢" },
  { a: "袋鼠", b: "小袋鼠", aTranslation: "Kangaroo", bTranslation: "Wallaby", aPronunciation: "袋鼠", bPronunciation: "小袋鼠" },
  { a: "考拉", b: "袋熊", aTranslation: "Koala", bTranslation: "Wombat", aPronunciation: "考拉", bPronunciation: "袋熊" },
  { a: "鴨嘴獸", b: "針鼹", aTranslation: "Platypus", bTranslation: "Echidna", aPronunciation: "鴨嘴獸", bPronunciation: "針鼹" },
  { a: "樹懶", b: "食蟻獸", aTranslation: "Sloth", bTranslation: "Anteater", aPronunciation: "樹懶", bPronunciation: "食蟻獸" },
  { a: "猴子", b: "黑猩猩", aTranslation: "Monkey", bTranslation: "Chimpanzee", aPronunciation: "hóu zi", bPronunciation: "hēi xīng xing" },
  { a: "大猩猩", b: "紅毛猩猩", aTranslation: "Gorilla", bTranslation: "Orangutan", aPronunciation: "dà xīng xing", bPronunciation: "紅毛猩猩" },
  { a: "狐猴", b: "貓鼬", aTranslation: "Lemur", bTranslation: "Meerkat", aPronunciation: "狐猴", bPronunciation: "貓鼬" },
  { a: "鱷魚", b: "短吻鱷", aTranslation: "Crocodile", bTranslation: "Alligator", aPronunciation: "鱷魚", bPronunciation: "短吻鱷" },
  { a: "蛇", b: "蜥蜴", aTranslation: "Snake", bTranslation: "Lizard", aPronunciation: "shé", bPronunciation: "xī yì" },
  { a: "海龜", b: "甲魚", aTranslation: "Turtle", bTranslation: "Softshell Turtle", aPronunciation: "海龜", bPronunciation: "甲魚" },
  { a: "青蛙", b: "蠑螈", aTranslation: "Frog", bTranslation: "Salamander", aPronunciation: "青蛙", bPronunciation: "蠑螈" },
  { a: "鯊魚", b: "鰩魚", aTranslation: "Shark", bTranslation: "Ray", aPronunciation: "鯊魚", bPronunciation: "鰩魚" },
  { a: "鯨魚", b: "海豚", aTranslation: "Whale", bTranslation: "Dolphin", aPronunciation: "鯨魚", bPronunciation: "海豚" },
  { a: "章魚", b: "烏賊", aTranslation: "Octopus", bTranslation: "Squid", aPronunciation: "章魚", bPronunciation: "烏賊" },
  { a: "螃蟹", b: "龍蝦", aTranslation: "Crab", bTranslation: "Lobster", aPronunciation: "螃蟹", bPronunciation: "龍蝦" },
  { a: "蝦", b: "對蝦", aTranslation: "Shrimp", bTranslation: "Prawn", aPronunciation: "xiā", bPronunciation: "duì xiā" },
  { a: "海馬", b: "海星", aTranslation: "Seahorse", bTranslation: "Starfish", aPronunciation: "海馬", bPronunciation: "海星" },
  { a: "水母", b: "珊瑚", aTranslation: "Jellyfish", bTranslation: "Coral", aPronunciation: "水母", bPronunciation: "珊瑚" },
  { a: "蜘蛛", b: "蠍子", aTranslation: "Spider", bTranslation: "Scorpion", aPronunciation: "蜘蛛", bPronunciation: "蠍子" },
  { a: "蜜蜂", b: "蝴蝶", aTranslation: "Bee", bTranslation: "Butterfly", aPronunciation: "蜜蜂", bPronunciation: "蝴蝶" },
  { a: "螞蟻", b: "白蟻", aTranslation: "Ant", bTranslation: "Termite", aPronunciation: "螞蟻", bPronunciation: "白蟻" },
  { a: "蚊子", b: "蒼蠅", aTranslation: "Mosquito", bTranslation: "Fly", aPronunciation: "wén zi", bPronunciation: "cāng ying" },
  { a: "蟋蟀", b: "蚱蜢", aTranslation: "Cricket", bTranslation: "Grasshopper", aPronunciation: "蟋蟀", bPronunciation: "蚱蜢" },
  { a: "蜻蜓", b: "豆娘", aTranslation: "Dragonfly", bTranslation: "Damselfly", aPronunciation: "蜻蜓", bPronunciation: "豆娘" },
  { a: "甲蟲", b: "瓢蟲", aTranslation: "Beetle", bTranslation: "Ladybug", aPronunciation: "甲蟲", bPronunciation: "瓢蟲" },
  { a: "蚯蚓", b: "毛毛蟲", aTranslation: "Worm", bTranslation: "Caterpillar", aPronunciation: "蚯蚓", bPronunciation: "毛毛蟲" },
  { a: "蝸牛", b: "蛞蝓", aTranslation: "Snail", bTranslation: "Slug", aPronunciation: "蝸牛", bPronunciation: "蛞蝓" },
  { a: "小提琴", b: "中提琴", aTranslation: "Violin", bTranslation: "Viola", aPronunciation: "小提琴", bPronunciation: "中提琴" },
  { a: "大提琴", b: "低音提琴", aTranslation: "Cello", bTranslation: "Double Bass", aPronunciation: "大提琴", bPronunciation: "低音提琴" },
  { a: "吉他", b: "尤克里里", aTranslation: "Guitar", bTranslation: "Ukulele", aPronunciation: "jí tā", bPronunciation: "尤克里里" },
  { a: "豎琴", b: "魯特琴", aTranslation: "Harp", bTranslation: "Lute", aPronunciation: "豎琴", bPronunciation: "魯特琴" },
  { a: "小號", b: "短號", aTranslation: "Trumpet", bTranslation: "Cornet", aPronunciation: "小號", bPronunciation: "短號" },
  { a: "長笛", b: "豎笛", aTranslation: "Flute", bTranslation: "Recorder", aPronunciation: "長笛", bPronunciation: "豎笛" },
  { a: "單簧管", b: "雙簧管", aTranslation: "Clarinet", bTranslation: "Oboe", aPronunciation: "單簧管", bPronunciation: "雙簧管" },
  { a: "薩克斯", b: "低音管", aTranslation: "Saxophone", bTranslation: "Bassoon", aPronunciation: "薩克斯", bPronunciation: "低音管" },
  { a: "鼓", b: "鈴鼓", aTranslation: "Drum", bTranslation: "Tambourine", aPronunciation: "gǔ", bPronunciation: "líng gǔ" },
  { a: "鋼琴", b: "管風琴", aTranslation: "Piano", bTranslation: "Organ", aPronunciation: "鋼琴", bPronunciation: "管風琴" }
];
