const words_zh_TW = [
  { civilian: "蘋果", spy: "梨", civilianTranslation: "Apple", spyTranslation: "Pear", civilianPronunciation: "píng guǒ", spyPronunciation: "lí" },
  { civilian: "橘子", spy: "檸檬", civilianTranslation: "Orange", spyTranslation: "Lemon", civilianPronunciation: "jú zi", spyPronunciation: "níng méng" },
  { civilian: "咖啡", spy: "茶", civilianTranslation: "Coffee", spyTranslation: "Tea", civilianPronunciation: "kā fēi", spyPronunciation: "chá" },
  { civilian: "卡布奇諾", spy: "拿鐵", civilianTranslation: "Cappuccino", spyTranslation: "Latte", civilianPronunciation: "kǎ bù qí nuò", spyPronunciation: "ná tiě" },
  { civilian: "披薩", spy: "漢堡", civilianTranslation: "Pizza", spyTranslation: "Hamburger", civilianPronunciation: "pī sà", spyPronunciation: "hàn bǎo" },
  { civilian: "麵包", spy: "米飯", civilianTranslation: "Bread", spyTranslation: "Rice", civilianPronunciation: "miàn bāo", spyPronunciation: "mǐ fàn" },
  { civilian: "牛奶", spy: "果汁", civilianTranslation: "Milk", spyTranslation: "Juice", civilianPronunciation: "niú nǎi", spyPronunciation: "guǒ zhī" },
  { civilian: "奶油", spy: "起司", civilianTranslation: "Butter", spyTranslation: "Cheese", civilianPronunciation: "nǎi yóu", spyPronunciation: "qǐ sī" },
  { civilian: "冰淇淋", spy: "蛋糕", civilianTranslation: "Ice Cream", spyTranslation: "Cake", civilianPronunciation: "bīng qí lín", spyPronunciation: "dàn gāo" },
  { civilian: "可樂", spy: "雪碧", civilianTranslation: "Cola", spyTranslation: "Sprite", civilianPronunciation: "kě lè", spyPronunciation: "xuě bì" },
  { civilian: "西瓜", spy: "哈密瓜", civilianTranslation: "Watermelon", spyTranslation: "Melon", civilianPronunciation: "xī guā", spyPronunciation: "hā mì guā" },
  { civilian: "草莓", spy: "櫻桃", civilianTranslation: "Strawberry", spyTranslation: "Cherry", civilianPronunciation: "cǎo méi", spyPronunciation: "yīng táo" },
  { civilian: "牛排", spy: "豬排", civilianTranslation: "Steak", spyTranslation: "Pork Chop", civilianPronunciation: "niú pái", spyPronunciation: "zhū pái" },
  { civilian: "麵條", spy: "義大利麵", civilianTranslation: "Noodles", spyTranslation: "Pasta", civilianPronunciation: "miàn tiáo", spyPronunciation: "yì dà lì miàn" },
  { civilian: "壽司", spy: "生魚片", civilianTranslation: "Sushi", spyTranslation: "Sashimi", civilianPronunciation: "shòu sī", spyPronunciation: "shēng yú piàn" },
  { civilian: "巧克力", spy: "糖果", civilianTranslation: "Chocolate", spyTranslation: "Candy", civilianPronunciation: "qiǎo kè lì", spyPronunciation: "táng guǒ" },
  { civilian: "馬鈴薯", spy: "地瓜", civilianTranslation: "Potato", spyTranslation: "Sweet Potato", civilianPronunciation: "mǎ líng shǔ", spyPronunciation: "dì guā" },
  { civilian: "洋蔥", spy: "大蒜", civilianTranslation: "Onion", spyTranslation: "Garlic", civilianPronunciation: "yáng cōng", spyPronunciation: "dà suàn" },
  { civilian: "番茄", spy: "胡蘿蔔", civilianTranslation: "Tomato", spyTranslation: "Carrot", civilianPronunciation: "fān qié", spyPronunciation: "hú luó bó" },
  { civilian: "湯", spy: "燉菜", civilianTranslation: "Soup", spyTranslation: "Stew", civilianPronunciation: "tāng", spyPronunciation: "dùn cài" },
  { civilian: "老虎", spy: "獅子", civilianTranslation: "Tiger", spyTranslation: "Lion", civilianPronunciation: "lǎo hǔ", spyPronunciation: "shī zi" },
  { civilian: "鯊魚", spy: "海豚", civilianTranslation: "Shark", spyTranslation: "Dolphin", civilianPronunciation: "shā yú", spyPronunciation: "hǎi tún" },
  { civilian: "貓頭鷹", spy: "老鷹", civilianTranslation: "Owl", spyTranslation: "Eagle", civilianPronunciation: "māo tóu yīng", spyPronunciation: "lǎo yīng" },
  { civilian: "老鼠", spy: "田鼠", civilianTranslation: "Mouse", spyTranslation: "Rat", civilianPronunciation: "lǎo shǔ", spyPronunciation: "tián shǔ" },
  { civilian: "兔子", spy: "倉鼠", civilianTranslation: "Rabbit", spyTranslation: "Hamster", civilianPronunciation: "tù zi", spyPronunciation: "cāng shǔ" },
  { civilian: "馬", spy: "驢", civilianTranslation: "Horse", spyTranslation: "Donkey", civilianPronunciation: "mǎ", spyPronunciation: "lǘ" },
  { civilian: "乳牛", spy: "綿羊", civilianTranslation: "Cow", spyTranslation: "Sheep", civilianPronunciation: "rǔ niú", spyPronunciation: "mián yáng" },
  { civilian: "豬", spy: "山羊", civilianTranslation: "Pig", spyTranslation: "Goat", civilianPronunciation: "zhū", spyPronunciation: "shān yáng" },
  { civilian: "企鵝", spy: "海豹", civilianTranslation: "Penguin", spyTranslation: "Seal", civilianPronunciation: "qǐ é", spyPronunciation: "hǎi bào" },
  { civilian: "蝴蝶", spy: "飛蛾", civilianTranslation: "Butterfly", spyTranslation: "Moth", civilianPronunciation: "hú dié", spyPronunciation: "fēi é" },
  { civilian: "蜜蜂", spy: "黃蜂", civilianTranslation: "Bee", spyTranslation: "Wasp", civilianPronunciation: "mì fēng", spyPronunciation: "huáng fēng" },
  { civilian: "蜘蛛", spy: "螞蟻", civilianTranslation: "Spider", spyTranslation: "Ant", civilianPronunciation: "zhī zhū", spyPronunciation: "mǎ yǐ" },
  { civilian: "海龜", spy: "烏龜", civilianTranslation: "Turtle", spyTranslation: "Tortoise", civilianPronunciation: "hǎi guī", spyPronunciation: "wū guī" },
  { civilian: "青蛙", spy: "蟾蜍", civilianTranslation: "Frog", spyTranslation: "Toad", civilianPronunciation: "qīng wā", spyPronunciation: "chán chú" },
  { civilian: "猴子", spy: "大猩猩", civilianTranslation: "Monkey", spyTranslation: "Gorilla", civilianPronunciation: "hóu zi", spyPronunciation: "dà xīng xīng" },
  { civilian: "熊", spy: "熊貓", civilianTranslation: "Bear", spyTranslation: "Panda", civilianPronunciation: "xióng", spyPronunciation: "xióng māo" },
  { civilian: "狐狸", spy: "狼", civilianTranslation: "Fox", spyTranslation: "Wolf", civilianPronunciation: "hú lí", spyPronunciation: "láng" },
  { civilian: "鴨子", spy: "鵝", civilianTranslation: "Duck", spyTranslation: "Goose", civilianPronunciation: "yā zi", spyPronunciation: "é" },
  { civilian: "狗", spy: "貓", civilianTranslation: "Dog", spyTranslation: "Cat", civilianPronunciation: "gǒu", spyPronunciation: "māo" },
  { civilian: "鯨魚", spy: "鯊魚", civilianTranslation: "Whale", spyTranslation: "Shark", civilianPronunciation: "jīng yú", spyPronunciation: "shā yú" },
  { civilian: "自行車", spy: "摩托車", civilianTranslation: "Bicycle", spyTranslation: "Motorbike", civilianPronunciation: "zì xíng chē", spyPronunciation: "mó tuō chē" },
  { civilian: "汽車", spy: "卡車", civilianTranslation: "Car", spyTranslation: "Truck", civilianPronunciation: "qì chē", spyPronunciation: "kǎ chē" },
  { civilian: "公車", spy: "計程車", civilianTranslation: "Bus", spyTranslation: "Taxi", civilianPronunciation: "gōng chē", spyPronunciation: "jì chéng chē" },
  { civilian: "火車", spy: "捷運", civilianTranslation: "Train", spyTranslation: "Subway", civilianPronunciation: "huǒ chē", spyPronunciation: "jié yùn" },
  { civilian: "飛機", spy: "直升機", civilianTranslation: "Airplane", spyTranslation: "Helicopter", civilianPronunciation: "fēi jī", spyPronunciation: "zhí shēng jī" },
  { civilian: "小船", spy: "輪船", civilianTranslation: "Boat", spyTranslation: "Ship", civilianPronunciation: "xiǎo chuán", spyPronunciation: "lún chuán" },
  { civilian: "獨木舟", spy: "皮划艇", civilianTranslation: "Canoe", spyTranslation: "Kayak", civilianPronunciation: "dú mù zhōu", spyPronunciation: "pí huá tǐng" },
  { civilian: "滑板", spy: "直排輪", civilianTranslation: "Skateboard", spyTranslation: "Rollerblades", civilianPronunciation: "huá bǎn", spyPronunciation: "zhí pái lún" },
  { civilian: "滑板車", spy: "平衡車", civilianTranslation: "Scooter", spyTranslation: "Hoverboard", civilianPronunciation: "huá bǎn chē", spyPronunciation: "píng héng chē" },
  { civilian: "救護車", spy: "消防車", civilianTranslation: "Ambulance", spyTranslation: "Fire Truck", civilianPronunciation: "jiù hù chē", spyPronunciation: "xiāo fáng chē" },
  { civilian: "椅子", spy: "凳子", civilianTranslation: "Chair", spyTranslation: "Stool", civilianPronunciation: "yǐ zi", spyPronunciation: "dèng zi" },
  { civilian: "沙發", spy: "扶手椅", civilianTranslation: "Sofa", spyTranslation: "Armchair", civilianPronunciation: "shā fā", spyPronunciation: "fú shǒu yǐ" },
  { civilian: "書桌", spy: "桌子", civilianTranslation: "Desk", spyTranslation: "Table", civilianPronunciation: "shū zhuō", spyPronunciation: "zhuō zi" },
  { civilian: "床", spy: "床墊", civilianTranslation: "Bed", spyTranslation: "Mattress", civilianPronunciation: "chuáng", spyPronunciation: "chuáng diàn" },
  { civilian: "衣櫥", spy: "壁櫥", civilianTranslation: "Wardrobe", spyTranslation: "Closet", civilianPronunciation: "yī chú", spyPronunciation: "bì chú" },
  { civilian: "書", spy: "雜誌", civilianTranslation: "Book", spyTranslation: "Magazine", civilianPronunciation: "shū", spyPronunciation: "zá zhì" },
  { civilian: "筆記本", spy: "日記本", civilianTranslation: "Notebook", spyTranslation: "Diary", civilianPronunciation: "bǐ jì běn", spyPronunciation: "rì jì běn" },
  { civilian: "鋼筆", spy: "鉛筆", civilianTranslation: "Pen", spyTranslation: "Pencil", civilianPronunciation: "gāng bǐ", spyPronunciation: "qiān bǐ" },
  { civilian: "麥克筆", spy: "螢光筆", civilianTranslation: "Marker", spyTranslation: "Highlighter", civilianPronunciation: "mài kè bǐ", spyPronunciation: "yíng guāng bǐ" },
  { civilian: "杯子", spy: "玻璃杯", civilianTranslation: "Cup", spyTranslation: "Glass", civilianPronunciation: "bēi zi", spyPronunciation: "bō lí bēi" },
  { civilian: "盤子", spy: "碗", civilianTranslation: "Plate", spyTranslation: "Bowl", civilianPronunciation: "pán zi", spyPronunciation: "wǎn" },
  { civilian: "湯匙", spy: "叉子", civilianTranslation: "Spoon", spyTranslation: "Fork", civilianPronunciation: "tāng shi", spyPronunciation: "chā zi" },
  { civilian: "刀", spy: "劍", civilianTranslation: "Knife", spyTranslation: "Sword", civilianPronunciation: "dāo", spyPronunciation: "jiàn" },
  { civilian: "時鐘", spy: "手錶", civilianTranslation: "Clock", spyTranslation: "Watch", civilianPronunciation: "shí zhōng", spyPronunciation: "shǒu biǎo" },
  { civilian: "電視", spy: "螢幕", civilianTranslation: "Television", spyTranslation: "Monitor", civilianPronunciation: "diàn shì", spyPronunciation: "yíng mù" },
  { civilian: "筆記型電腦", spy: "平板電腦", civilianTranslation: "Laptop", spyTranslation: "Tablet", civilianPronunciation: "bǐ jì xíng diàn nǎo", spyPronunciation: "píng bǎn diàn nǎo" },
  { civilian: "智慧型手機", spy: "電話", civilianTranslation: "Smartphone", spyTranslation: "Telephone", civilianPronunciation: "zhì huì xíng shǒu jī", spyPronunciation: "diàn huà" },
  { civilian: "耳機", spy: "麥克風", civilianTranslation: "Earphones", spyTranslation: "Microphone", civilianPronunciation: "ěr jī", spyPronunciation: "mài kè fēng" },
  { civilian: "窗戶", spy: "門", civilianTranslation: "Window", spyTranslation: "Door", civilianPronunciation: "chuāng hù", spyPronunciation: "mén" },
  { civilian: "屋頂", spy: "天花板", civilianTranslation: "Roof", spyTranslation: "Ceiling", civilianPronunciation: "wū dǐng", spyPronunciation: "tiān huā bǎn" },
  { civilian: "大衣", spy: "夾克", civilianTranslation: "Coat", spyTranslation: "Jacket", civilianPronunciation: "dà yī", spyPronunciation: "jiā kè" },
  { civilian: "毛衣", spy: "帽T", civilianTranslation: "Sweater", spyTranslation: "Hoodie", civilianPronunciation: "máo yī", spyPronunciation: "mào T" },
  { civilian: "襯衫", spy: "T恤", civilianTranslation: "Shirt", spyTranslation: "T-shirt", civilianPronunciation: "chèn shān", spyPronunciation: "T xù" },
  { civilian: "長褲", spy: "牛仔褲", civilianTranslation: "Trousers", spyTranslation: "Jeans", civilianPronunciation: "zhǎng kù", spyPronunciation: "niú zǎi kù" },
  { civilian: "短褲", spy: "裙子", civilianTranslation: "Shorts", spyTranslation: "Skirt", civilianPronunciation: "duǎn kù", spyPronunciation: "qún zi" },
  { civilian: "鞋子", spy: "靴子", civilianTranslation: "Shoes", spyTranslation: "Boots", civilianPronunciation: "xié zi", spyPronunciation: "xuē zi" },
  { civilian: "運動鞋", spy: "涼鞋", civilianTranslation: "Sneakers", spyTranslation: "Sandals", civilianPronunciation: "yùn dòng xié", spyPronunciation: "liáng xié" },
  { civilian: "襪子", spy: "絲襪", civilianTranslation: "Socks", spyTranslation: "Stockings", civilianPronunciation: "wà zi", spyPronunciation: "sī wà" },
  { civilian: "帽子", spy: "鴨舌帽", civilianTranslation: "Hat", spyTranslation: "Cap", civilianPronunciation: "mào zi", spyPronunciation: "yā shé mào" },
  { civilian: "手套", spy: "連指手套", civilianTranslation: "Gloves", spyTranslation: "Mittens", civilianPronunciation: "shǒu tào", spyPronunciation: "lián zhǐ shǒu tào" },
  { civilian: "圖書館", spy: "書店", civilianTranslation: "Library", spyTranslation: "Bookstore", civilianPronunciation: "tú shū guǎn", spyPronunciation: "shū diàn" },
  { civilian: "醫院", spy: "診所", civilianTranslation: "Hospital", spyTranslation: "Clinic", civilianPronunciation: "yī yuàn", spyPronunciation: "zhěn suǒ" },
  { civilian: "學校", spy: "大學", civilianTranslation: "School", spyTranslation: "University", civilianPronunciation: "xué xiào", spyPronunciation: "dà xué" },
  { civilian: "公園", spy: "花園", civilianTranslation: "Park", spyTranslation: "Garden", civilianPronunciation: "gōng yuán", spyPronunciation: "huā yuán" },
  { civilian: "河", spy: "湖", civilianTranslation: "River", spyTranslation: "Lake", civilianPronunciation: "hé", spyPronunciation: "hú" },
  { civilian: "海", spy: "海洋", civilianTranslation: "Sea", spyTranslation: "Ocean", civilianPronunciation: "hǎi", spyPronunciation: "hǎi yáng" },
  { civilian: "山", spy: "丘陵", civilianTranslation: "Mountain", spyTranslation: "Hill", civilianPronunciation: "shān", spyPronunciation: "qiū líng" },
  { civilian: "森林", spy: "樹林", civilianTranslation: "Forest", spyTranslation: "Woods", civilianPronunciation: "sēn lín", spyPronunciation: "shù lín" },
  { civilian: "島嶼", spy: "半島", civilianTranslation: "Island", spyTranslation: "Peninsula", civilianPronunciation: "dǎo yǔ", spyPronunciation: "bàn dǎo" },
  { civilian: "沙漠", spy: "海灘", civilianTranslation: "Desert", spyTranslation: "Beach", civilianPronunciation: "shā mò", spyPronunciation: "hǎi tān" },
  { civilian: "醫生", spy: "護士", civilianTranslation: "Doctor", spyTranslation: "Nurse", civilianPronunciation: "yī shēng", spyPronunciation: "hù shì" },
  { civilian: "老師", spy: "教授", civilianTranslation: "Teacher", spyTranslation: "Professor", civilianPronunciation: "lǎo shī", spyPronunciation: "jiào shòu" },
  { civilian: "警察", spy: "偵探", civilianTranslation: "Police", spyTranslation: "Detective", civilianPronunciation: "jǐng chá", spyPronunciation: "zhēn tàn" },
  { civilian: "歌手", spy: "演員", civilianTranslation: "Singer", spyTranslation: "Actor", civilianPronunciation: "gē shǒu", spyPronunciation: "yǎn yuán" },
  { civilian: "作家", spy: "記者", civilianTranslation: "Writer", spyTranslation: "Journalist", civilianPronunciation: "zuò jiā", spyPronunciation: "jì zhě" },
  { civilian: "廚師", spy: "麵包師", civilianTranslation: "Chef", spyTranslation: "Baker", civilianPronunciation: "chú shī", spyPronunciation: "miàn bāo shī" },
  { civilian: "飛行員", spy: "船長", civilianTranslation: "Pilot", spyTranslation: "Captain", civilianPronunciation: "fēi xíng yuán", spyPronunciation: "chuán zhǎng" },
  { civilian: "學生", spy: "小學生", civilianTranslation: "Student", spyTranslation: "Pupil", civilianPronunciation: "xué shēng", spyPronunciation: "xiǎo xué shēng" },
  { civilian: "國王", spy: "皇帝", civilianTranslation: "King", spyTranslation: "Emperor", civilianPronunciation: "guó wáng", spyPronunciation: "huáng dì" },
  { civilian: "農民", spy: "漁夫", civilianTranslation: "Farmer", spyTranslation: "Fisherman", civilianPronunciation: "nóng mín", spyPronunciation: "yú fū" },
  { civilian: "吉他", spy: "小提琴", civilianTranslation: "Guitar", spyTranslation: "Violin", civilianPronunciation: "jí tā", spyPronunciation: "xiǎo tí qín" },
  { civilian: "鋼琴", spy: "電子琴", civilianTranslation: "Piano", spyTranslation: "Keyboard", civilianPronunciation: "gāng qín", spyPronunciation: "diàn zi qín" },
  { civilian: "長笛", spy: "單簧管", civilianTranslation: "Flute", spyTranslation: "Clarinet", civilianPronunciation: "zhǎng dí", spyPronunciation: "dān huáng guǎn" },
  { civilian: "小號", spy: "薩克斯風", civilianTranslation: "Trumpet", spyTranslation: "Saxophone", civilianPronunciation: "xiǎo hào", spyPronunciation: "sà kè sī fēng" },
  { civilian: "鼓", spy: "銅鈸", civilianTranslation: "Drum", spyTranslation: "Cymbal", civilianPronunciation: "gǔ", spyPronunciation: "tóng bó" },
  { civilian: "繪畫", spy: "素描", civilianTranslation: "Painting", spyTranslation: "Drawing", civilianPronunciation: "huì huà", spyPronunciation: "sù miáo" },
  { civilian: "雕塑", spy: "雕像", civilianTranslation: "Sculpture", spyTranslation: "Statue", civilianPronunciation: "diāo sù", spyPronunciation: "diāo xiàng" },
  { civilian: "照片", spy: "海報", civilianTranslation: "Photograph", spyTranslation: "Poster", civilianPronunciation: "zhào piān", spyPronunciation: "hǎi bào" },
  { civilian: "博物館", spy: "畫廊", civilianTranslation: "Museum", spyTranslation: "Gallery", civilianPronunciation: "bó wù guǎn", spyPronunciation: "huà láng" },
  { civilian: "電影", spy: "舞台劇", civilianTranslation: "Movie", spyTranslation: "Play", civilianPronunciation: "diàn yǐng", spyPronunciation: "wǔ tái jù" }
];
