const words_zh_CN = [
  { civilian: "苹果", spy: "梨", civilianTranslation: "Apple", spyTranslation: "Pear", civilianPronunciation: "píng guǒ", spyPronunciation: "lí" },
  { civilian: "橘子", spy: "柠檬", civilianTranslation: "Orange", spyTranslation: "Lemon", civilianPronunciation: "jú zi", spyPronunciation: "níng méng" },
  { civilian: "咖啡", spy: "茶", civilianTranslation: "Coffee", spyTranslation: "Tea", civilianPronunciation: "kā fēi", spyPronunciation: "chá" },
  { civilian: "卡布奇诺", spy: "拿铁", civilianTranslation: "Cappuccino", spyTranslation: "Latte", civilianPronunciation: "kǎ bù qí nuò", spyPronunciation: "ná tiě" },
  { civilian: "披萨", spy: "汉堡包", civilianTranslation: "Pizza", spyTranslation: "Hamburger", civilianPronunciation: "pī sà", spyPronunciation: "hàn bǎo bāo" },
  { civilian: "面包", spy: "米饭", civilianTranslation: "Bread", spyTranslation: "Rice", civilianPronunciation: "miàn bāo", spyPronunciation: "mǐ fàn" },
  { civilian: "牛奶", spy: "果汁", civilianTranslation: "Milk", spyTranslation: "Juice", civilianPronunciation: "niú nǎi", spyPronunciation: "guǒ zhī" },
  { civilian: "黄油", spy: "奶酪", civilianTranslation: "Butter", spyTranslation: "Cheese", civilianPronunciation: "huáng yóu", spyPronunciation: "nǎi lào" },
  { civilian: "冰淇淋", spy: "蛋糕", civilianTranslation: "Ice Cream", spyTranslation: "Cake", civilianPronunciation: "bīng qí lín", spyPronunciation: "dàn gāo" },
  { civilian: "可乐", spy: "雪碧", civilianTranslation: "Cola", spyTranslation: "Sprite", civilianPronunciation: "kě lè", spyPronunciation: "xuě bì" },
  { civilian: "西瓜", spy: "哈密瓜", civilianTranslation: "Watermelon", spyTranslation: "Melon", civilianPronunciation: "xī guā", spyPronunciation: "hā mì guā" },
  { civilian: "草莓", spy: "樱桃", civilianTranslation: "Strawberry", spyTranslation: "Cherry", civilianPronunciation: "cǎo méi", spyPronunciation: "yīng táo" },
  { civilian: "牛排", spy: "猪排", civilianTranslation: "Steak", spyTranslation: "Pork Chop", civilianPronunciation: "niú pái", spyPronunciation: "zhū pái" },
  { civilian: "面条", spy: "意大利面", civilianTranslation: "Noodles", spyTranslation: "Pasta", civilianPronunciation: "miàn tiáo", spyPronunciation: "yì dà lì miàn" },
  { civilian: "寿司", spy: "生鱼片", civilianTranslation: "Sushi", spyTranslation: "Sashimi", civilianPronunciation: "shòu sī", spyPronunciation: "shēng yú piàn" },
  { civilian: "巧克力", spy: "糖果", civilianTranslation: "Chocolate", spyTranslation: "Candy", civilianPronunciation: "qiǎo kè lì", spyPronunciation: "táng guǒ" },
  { civilian: "土豆", spy: "红薯", civilianTranslation: "Potato", spyTranslation: "Sweet Potato", civilianPronunciation: "tǔ dòu", spyPronunciation: "hóng shǔ" },
  { civilian: "洋葱", spy: "大蒜", civilianTranslation: "Onion", spyTranslation: "Garlic", civilianPronunciation: "yáng cōng", spyPronunciation: "dà suàn" },
  { civilian: "西红柿", spy: "胡萝卜", civilianTranslation: "Tomato", spyTranslation: "Carrot", civilianPronunciation: "xī hóng shì", spyPronunciation: "hú luó bo" },
  { civilian: "汤", spy: "炖菜", civilianTranslation: "Soup", spyTranslation: "Stew", civilianPronunciation: "tāng", spyPronunciation: "dùn cài" },
  { civilian: "老虎", spy: "狮子", civilianTranslation: "Tiger", spyTranslation: "Lion", civilianPronunciation: "lǎo hǔ", spyPronunciation: "shī zi" },
  { civilian: "鲨鱼", spy: "海豚", civilianTranslation: "Shark", spyTranslation: "Dolphin", civilianPronunciation: "shā yú", spyPronunciation: "hǎi tún" },
  { civilian: "猫头鹰", spy: "老鹰", civilianTranslation: "Owl", spyTranslation: "Eagle", civilianPronunciation: "māo tóu yīng", spyPronunciation: "lǎo yīng" },
  { civilian: "老鼠", spy: "田鼠", civilianTranslation: "Mouse", spyTranslation: "Rat", civilianPronunciation: "lǎo shǔ", spyPronunciation: "tián shǔ" },
  { civilian: "兔子", spy: "仓鼠", civilianTranslation: "Rabbit", spyTranslation: "Hamster", civilianPronunciation: "tù zi", spyPronunciation: "cāng shǔ" },
  { civilian: "马", spy: "驴", civilianTranslation: "Horse", spyTranslation: "Donkey", civilianPronunciation: "mǎ", spyPronunciation: "lǘ" },
  { civilian: "奶牛", spy: "绵羊", civilianTranslation: "Cow", spyTranslation: "Sheep", civilianPronunciation: "nǎi niú", spyPronunciation: "mián yáng" },
  { civilian: "猪", spy: "山羊", civilianTranslation: "Pig", spyTranslation: "Goat", civilianPronunciation: "zhū", spyPronunciation: "shān yáng" },
  { civilian: "企鹅", spy: "海豹", civilianTranslation: "Penguin", spyTranslation: "Seal", civilianPronunciation: "qǐ é", spyPronunciation: "hǎi bào" },
  { civilian: "蝴蝶", spy: "飞蛾", civilianTranslation: "Butterfly", spyTranslation: "Moth", civilianPronunciation: "hú dié", spyPronunciation: "fēi é" },
  { civilian: "蜜蜂", spy: "黄蜂", civilianTranslation: "Bee", spyTranslation: "Wasp", civilianPronunciation: "mì fēng", spyPronunciation: "huáng fēng" },
  { civilian: "蜘蛛", spy: "蚂蚁", civilianTranslation: "Spider", spyTranslation: "Ant", civilianPronunciation: "zhī zhū", spyPronunciation: "mǎ yǐ" },
  { civilian: "海龟", spy: "乌龟", civilianTranslation: "Turtle", spyTranslation: "Tortoise", civilianPronunciation: "hǎi guī", spyPronunciation: "wū guī" },
  { civilian: "青蛙", spy: "蟾蜍", civilianTranslation: "Frog", spyTranslation: "Toad", civilianPronunciation: "qīng wā", spyPronunciation: "chán chú" },
  { civilian: "猴子", spy: "大猩猩", civilianTranslation: "Monkey", spyTranslation: "Gorilla", civilianPronunciation: "hóu zi", spyPronunciation: "dà xīng xīng" },
  { civilian: "熊", spy: "熊猫", civilianTranslation: "Bear", spyTranslation: "Panda", civilianPronunciation: "xióng", spyPronunciation: "xióng māo" },
  { civilian: "狐狸", spy: "狼", civilianTranslation: "Fox", spyTranslation: "Wolf", civilianPronunciation: "hú lí", spyPronunciation: "láng" },
  { civilian: "鸭子", spy: "鹅", civilianTranslation: "Duck", spyTranslation: "Goose", civilianPronunciation: "yā zi", spyPronunciation: "é" },
  { civilian: "狗", spy: "猫", civilianTranslation: "Dog", spyTranslation: "Cat", civilianPronunciation: "gǒu", spyPronunciation: "māo" },
  { civilian: "鲸鱼", spy: "鲨鱼", civilianTranslation: "Whale", spyTranslation: "Shark", civilianPronunciation: "jīng yú", spyPronunciation: "shā yú" },
  { civilian: "自行车", spy: "摩托车", civilianTranslation: "Bicycle", spyTranslation: "Motorbike", civilianPronunciation: "zì xíng chē", spyPronunciation: "mó tuō chē" },
  { civilian: "汽车", spy: "卡车", civilianTranslation: "Car", spyTranslation: "Truck", civilianPronunciation: "qì chē", spyPronunciation: "kǎ chē" },
  { civilian: "公交车", spy: "出租车", civilianTranslation: "Bus", spyTranslation: "Taxi", civilianPronunciation: "gōng jiāo chē", spyPronunciation: "chū zū chē" },
  { civilian: "火车", spy: "地铁", civilianTranslation: "Train", spyTranslation: "Subway", civilianPronunciation: "huǒ chē", spyPronunciation: "dì tiě" },
  { civilian: "飞机", spy: "直升机", civilianTranslation: "Airplane", spyTranslation: "Helicopter", civilianPronunciation: "fēi jī", spyPronunciation: "zhí shēng jī" },
  { civilian: "小船", spy: "轮船", civilianTranslation: "Boat", spyTranslation: "Ship", civilianPronunciation: "xiǎo chuán", spyPronunciation: "lún chuán" },
  { civilian: "独木舟", spy: "皮划艇", civilianTranslation: "Canoe", spyTranslation: "Kayak", civilianPronunciation: "dú mù zhōu", spyPronunciation: "pí huá tǐng" },
  { civilian: "滑板", spy: "旱冰鞋", civilianTranslation: "Skateboard", spyTranslation: "Rollerblades", civilianPronunciation: "huá bǎn", spyPronunciation: "hàn bīng xié" },
  { civilian: "滑板车", spy: "平衡车", civilianTranslation: "Scooter", spyTranslation: "Hoverboard", civilianPronunciation: "huá bǎn chē", spyPronunciation: "píng héng chē" },
  { civilian: "救护车", spy: "消防车", civilianTranslation: "Ambulance", spyTranslation: "Fire Truck", civilianPronunciation: "jiù hù chē", spyPronunciation: "xiāo fáng chē" },
  { civilian: "椅子", spy: "凳子", civilianTranslation: "Chair", spyTranslation: "Stool", civilianPronunciation: "yǐ zi", spyPronunciation: "dèng zi" },
  { civilian: "沙发", spy: "扶手椅", civilianTranslation: "Sofa", spyTranslation: "Armchair", civilianPronunciation: "shā fā", spyPronunciation: "fú shǒu yǐ" },
  { civilian: "书桌", spy: "桌子", civilianTranslation: "Desk", spyTranslation: "Table", civilianPronunciation: "shū zhuō", spyPronunciation: "zhuō zi" },
  { civilian: "床", spy: "床垫", civilianTranslation: "Bed", spyTranslation: "Mattress", civilianPronunciation: "chuáng", spyPronunciation: "chuáng diàn" },
  { civilian: "衣柜", spy: "壁橱", civilianTranslation: "Wardrobe", spyTranslation: "Closet", civilianPronunciation: "yī guì", spyPronunciation: "bì chú" },
  { civilian: "书", spy: "杂志", civilianTranslation: "Book", spyTranslation: "Magazine", civilianPronunciation: "shū", spyPronunciation: "zá zhì" },
  { civilian: "笔记本", spy: "日记本", civilianTranslation: "Notebook", spyTranslation: "Diary", civilianPronunciation: "bǐ jì běn", spyPronunciation: "rì jì běn" },
  { civilian: "钢笔", spy: "铅笔", civilianTranslation: "Pen", spyTranslation: "Pencil", civilianPronunciation: "gāng bǐ", spyPronunciation: "qiān bǐ" },
  { civilian: "记号笔", spy: "荧光笔", civilianTranslation: "Marker", spyTranslation: "Highlighter", civilianPronunciation: "jì hào bǐ", spyPronunciation: "yíng guāng bǐ" },
  { civilian: "杯子", spy: "玻璃杯", civilianTranslation: "Cup", spyTranslation: "Glass", civilianPronunciation: "bēi zi", spyPronunciation: "bō lí bēi" },
  { civilian: "盘子", spy: "碗", civilianTranslation: "Plate", spyTranslation: "Bowl", civilianPronunciation: "pán zi", spyPronunciation: "wǎn" },
  { civilian: "勺子", spy: "叉子", civilianTranslation: "Spoon", spyTranslation: "Fork", civilianPronunciation: "sháo zi", spyPronunciation: "chā zi" },
  { civilian: "刀", spy: "剑", civilianTranslation: "Knife", spyTranslation: "Sword", civilianPronunciation: "dāo", spyPronunciation: "jiàn" },
  { civilian: "钟表", spy: "手表", civilianTranslation: "Clock", spyTranslation: "Watch", civilianPronunciation: "zhōng biǎo", spyPronunciation: "shǒu biǎo" },
  { civilian: "电视", spy: "显示器", civilianTranslation: "Television", spyTranslation: "Monitor", civilianPronunciation: "diàn shì", spyPronunciation: "xiǎn shì qì" },
  { civilian: "笔记本电脑", spy: "平板电脑", civilianTranslation: "Laptop", spyTranslation: "Tablet", civilianPronunciation: "bǐ jì běn diàn nǎo", spyPronunciation: "píng bǎn diàn nǎo" },
  { civilian: "智能手机", spy: "电话", civilianTranslation: "Smartphone", spyTranslation: "Telephone", civilianPronunciation: "zhì néng shǒu jī", spyPronunciation: "diàn huà" },
  { civilian: "收音机", spy: "扬声器", civilianTranslation: "Radio", spyTranslation: "Speaker", civilianPronunciation: "shōu yīn jī", spyPronunciation: "yáng shēng qì" },
  { civilian: "窗户", spy: "门", civilianTranslation: "Window", spyTranslation: "Door", civilianPronunciation: "chuāng hù", spyPronunciation: "mén" },
  { civilian: "屋顶", spy: "天花板", civilianTranslation: "Roof", spyTranslation: "Ceiling", civilianPronunciation: "wū dǐng", spyPronunciation: "tiān huā bǎn" },
  { civilian: "大衣", spy: "夹克", civilianTranslation: "Coat", spyTranslation: "Jacket", civilianPronunciation: "dà yī", spyPronunciation: "jiá kè" },
  { civilian: "毛衣", spy: "卫衣", civilianTranslation: "Sweater", spyTranslation: "Hoodie", civilianPronunciation: "máo yī", spyPronunciation: "wèi yī" },
  { civilian: "衬衫", spy: "T恤", civilianTranslation: "Shirt", spyTranslation: "T-shirt", civilianPronunciation: "chèn shān", spyPronunciation: "T xù" },
  { civilian: "长裤", spy: "牛仔裤", civilianTranslation: "Trousers", spyTranslation: "Jeans", civilianPronunciation: "cháng kù", spyPronunciation: "niú zǎi kù" },
  { civilian: "短裤", spy: "裙子", civilianTranslation: "Shorts", spyTranslation: "Skirt", civilianPronunciation: "duǎn kù", spyPronunciation: "qún zi" },
  { civilian: "鞋子", spy: "靴子", civilianTranslation: "Shoes", spyTranslation: "Boots", civilianPronunciation: "xié zi", spyPronunciation: "xuē zi" },
  { civilian: "运动鞋", spy: "凉鞋", civilianTranslation: "Sneakers", spyTranslation: "Sandals", civilianPronunciation: "yùn dòng xié", spyPronunciation: "liáng xié" },
  { civilian: "袜子", spy: "丝袜", civilianTranslation: "Socks", spyTranslation: "Stockings", civilianPronunciation: "wà zi", spyPronunciation: "sī wà" },
  { civilian: "帽子", spy: "棒球帽", civilianTranslation: "Hat", spyTranslation: "Cap", civilianPronunciation: "mào zi", spyPronunciation: "bàng qiú mào" },
  { civilian: "手套", spy: "连指手套", civilianTranslation: "Gloves", spyTranslation: "Mittens", civilianPronunciation: "shǒu tào", spyPronunciation: "lián zhǐ shǒu tào" },
  { civilian: "图书馆", spy: "书店", civilianTranslation: "Library", spyTranslation: "Bookstore", civilianPronunciation: "tú shū guǎn", spyPronunciation: "shū diàn" },
  { civilian: "医院", spy: "诊所", civilianTranslation: "Hospital", spyTranslation: "Clinic", civilianPronunciation: "yī yuàn", spyPronunciation: "zhěn suǒ" },
  { civilian: "学校", spy: "大学", civilianTranslation: "School", spyTranslation: "University", civilianPronunciation: "xué xiào", spyPronunciation: "dà xué" },
  { civilian: "公园", spy: "花园", civilianTranslation: "Park", spyTranslation: "Garden", civilianPronunciation: "gōng yuán", spyPronunciation: "huā yuán" },
  { civilian: "河", spy: "湖", civilianTranslation: "River", spyTranslation: "Lake", civilianPronunciation: "hé", spyPronunciation: "hú" },
  { civilian: "海", spy: "海洋", civilianTranslation: "Sea", spyTranslation: "Ocean", civilianPronunciation: "hǎi", spyPronunciation: "hǎi yáng" },
  { civilian: "山", spy: "丘陵", civilianTranslation: "Mountain", spyTranslation: "Hill", civilianPronunciation: "shān", spyPronunciation: "qiū líng" },
  { civilian: "森林", spy: "树林", civilianTranslation: "Forest", spyTranslation: "Woods", civilianPronunciation: "sēn lín", spyPronunciation: "shù lín" },
  { civilian: "岛屿", spy: "半岛", civilianTranslation: "Island", spyTranslation: "Peninsula", civilianPronunciation: "dǎo yǔ", spyPronunciation: "bàn dǎo" },
  { civilian: "沙漠", spy: "海滩", civilianTranslation: "Desert", spyTranslation: "Beach", civilianPronunciation: "shā mò", spyPronunciation: "hǎi tān" },
  { civilian: "医生", spy: "护士", civilianTranslation: "Doctor", spyTranslation: "Nurse", civilianPronunciation: "yī shēng", spyPronunciation: "hù shì" },
  { civilian: "老师", spy: "教授", civilianTranslation: "Teacher", spyTranslation: "Professor", civilianPronunciation: "lǎo shī", spyPronunciation: "jiào shòu" },
  { civilian: "警察", spy: "侦探", civilianTranslation: "Police", spyTranslation: "Detective", civilianPronunciation: "jǐng chá", spyPronunciation: "zhēn tàn" },
  { civilian: "歌手", spy: "演员", civilianTranslation: "Singer", spyTranslation: "Actor", civilianPronunciation: "gē shǒu", spyPronunciation: "yǎn yuán" },
  { civilian: "作家", spy: "记者", civilianTranslation: "Writer", spyTranslation: "Journalist", civilianPronunciation: "zuò jiā", spyPronunciation: "jì zhě" },
  { civilian: "厨师", spy: "面包师", civilianTranslation: "Chef", spyTranslation: "Baker", civilianPronunciation: "chú shī", spyPronunciation: "miàn bāo shī" },
  { civilian: "飞行员", spy: "船长", civilianTranslation: "Pilot", spyTranslation: "Captain", civilianPronunciation: "fēi xíng yuán", spyPronunciation: "chuán zhǎng" },
  { civilian: "学生", spy: "小学生", civilianTranslation: "Student", spyTranslation: "Pupil", civilianPronunciation: "xué shēng", spyPronunciation: "xiǎo xué shēng" },
  { civilian: "国王", spy: "皇帝", civilianTranslation: "King", spyTranslation: "Emperor", civilianPronunciation: "guó wáng", spyPronunciation: "huáng dì" },
  { civilian: "农民", spy: "渔夫", civilianTranslation: "Farmer", spyTranslation: "Fisherman", civilianPronunciation: "nóng mín", spyPronunciation: "yú fū" },
  { civilian: "吉他", spy: "小提琴", civilianTranslation: "Guitar", spyTranslation: "Violin", civilianPronunciation: "jí tā", spyPronunciation: "xiǎo tí qín" },
  { civilian: "钢琴", spy: "电子琴", civilianTranslation: "Piano", spyTranslation: "Keyboard", civilianPronunciation: "gāng qín", spyPronunciation: "diàn zi qín" },
  { civilian: "长笛", spy: "单簧管", civilianTranslation: "Flute", spyTranslation: "Clarinet", civilianPronunciation: "cháng dí", spyPronunciation: "dān huáng guǎn" },
  { civilian: "小号", spy: "萨克斯", civilianTranslation: "Trumpet", spyTranslation: "Saxophone", civilianPronunciation: "xiǎo hào", spyPronunciation: "sà kè sī" },
  { civilian: "鼓", spy: "铜钹", civilianTranslation: "Drum", spyTranslation: "Cymbal", civilianPronunciation: "gǔ", spyPronunciation: "tóng bó" },
  { civilian: "绘画", spy: "素描", civilianTranslation: "Painting", spyTranslation: "Drawing", civilianPronunciation: "huì huà", spyPronunciation: "sù miáo" },
  { civilian: "雕塑", spy: "雕像", civilianTranslation: "Sculpture", spyTranslation: "Statue", civilianPronunciation: "diāo sù", spyPronunciation: "diāo xiàng" },
  { civilian: "相片", spy: "海报", civilianTranslation: "Photograph", spyTranslation: "Poster", civilianPronunciation: "xiàng piān", spyPronunciation: "hǎi bào" },
  { civilian: "博物馆", spy: "画廊", civilianTranslation: "Museum", spyTranslation: "Gallery", civilianPronunciation: "bó wù guǎn", spyPronunciation: "huà láng" },
  { civilian: "电影", spy: "话剧", civilianTranslation: "Movie", spyTranslation: "Play", civilianPronunciation: "diàn yǐng", spyPronunciation: "huà jù" },
  { civilian: "金", spy: "银", civilianTranslation: "Gold", spyTranslation: "Silver", civilianPronunciation: "jīn", spyPronunciation: "yín" },
  { civilian: "钻石", spy: "红宝石", civilianTranslation: "Diamond", spyTranslation: "Ruby", civilianPronunciation: "zuàn shí", spyPronunciation: "hóng bǎo shí" },
  { civilian: "雨", spy: "雪", civilianTranslation: "Rain", spyTranslation: "Snow", civilianPronunciation: "yǔ", spyPronunciation: "xuě" },
  { civilian: "风", spy: "风暴", civilianTranslation: "Wind", spyTranslation: "Storm", civilianPronunciation: "fēng", spyPronunciation: "fēng bào" },
  { civilian: "雷", spy: "闪电", civilianTranslation: "Thunder", spyTranslation: "Lightning", civilianPronunciation: "léi", spyPronunciation: "shǎn diàn" },
  { civilian: "城市", spy: "村庄", civilianTranslation: "City", spyTranslation: "Village", civilianPronunciation: "chéng shì", spyPronunciation: "cūn zhuāng" },
  { civilian: "街道", spy: "小巷", civilianTranslation: "Street", spyTranslation: "Alley", civilianPronunciation: "jiē dào", spyPronunciation: "xiǎo xiàng" },
  { civilian: "桥", spy: "隧道", civilianTranslation: "Bridge", spyTranslation: "Tunnel", civilianPronunciation: "qiáo", spyPronunciation: "suì dào" },
  { civilian: "房子", spy: "公寓", civilianTranslation: "House", spyTranslation: "Apartment", civilianPronunciation: "fáng zi", spyPronunciation: "gōng yù" },
  { civilian: "城堡", spy: "宫殿", civilianTranslation: "Castle", spyTranslation: "Palace", civilianPronunciation: "chéng bǎo", spyPronunciation: "gōng diàn" },
  { civilian: "酒店", spy: "旅馆", civilianTranslation: "Hotel", spyTranslation: "Inn", civilianPronunciation: "jiǔ diàn", spyPronunciation: "lǚ guǎn" },
  { civilian: "餐厅", spy: "咖啡馆", civilianTranslation: "Restaurant", spyTranslation: "Cafe", civilianPronunciation: "cān tīng", spyPronunciation: "kā fēi guǎn" },
  { civilian: "酒吧", spy: "酒馆", civilianTranslation: "Bar", spyTranslation: "Pub", civilianPronunciation: "jiǔ bā", spyPronunciation: "jiǔ guǎn" },
  { civilian: "超市", spy: "便利店", civilianTranslation: "Supermarket", spyTranslation: "Convenience Store", civilianPronunciation: "chāo shì", spyPronunciation: "biàn lì diàn" },
  { civilian: "百货公司", spy: "购物中心", civilianTranslation: "Department Store", spyTranslation: "Mall", civilianPronunciation: "bǎi huò gōng sī", spyPronunciation: "gòu wù zhōng xīn" },
  { civilian: "演唱会", spy: "音乐节", civilianTranslation: "Concert", spyTranslation: "Festival", civilianPronunciation: "yǎn chàng huì", spyPronunciation: "yīn yuè jié" },
  { civilian: "体育场", spy: "竞技场", civilianTranslation: "Stadium", spyTranslation: "Arena", civilianPronunciation: "tǐ yù chǎng", spyPronunciation: "jìng jì chǎng" },
  { civilian: "健身房", spy: "道场", civilianTranslation: "Gym", spyTranslation: "Dojo", civilianPronunciation: "jiàn shēn fáng", spyPronunciation: "dào chǎng" },
  { civilian: "游泳池", spy: "温泉", civilianTranslation: "Pool", spyTranslation: "Hot Spring", civilianPronunciation: "yóu yǒng chí", spyPronunciation: "wēn quán" },
  { civilian: "数学", spy: "科学", civilianTranslation: "Math", spyTranslation: "Science", civilianPronunciation: "shù xué", spyPronunciation: "kē xué" },
  { civilian: "历史", spy: "地理", civilianTranslation: "History", spyTranslation: "Geography", civilianPronunciation: "lì shǐ", spyPronunciation: "dì lǐ" },
  { civilian: "物理", spy: "化学", civilianTranslation: "Physics", spyTranslation: "Chemistry", civilianPronunciation: "wù lǐ", spyPronunciation: "huà xué" },
  { civilian: "生物学", spy: "解剖学", civilianTranslation: "Biology", spyTranslation: "Anatomy", civilianPronunciation: "shēng wù xué", spyPronunciation: "jiě pōu xué" },
  { civilian: "美术", spy: "音乐", civilianTranslation: "Art", spyTranslation: "Music", civilianPronunciation: "měi shù", spyPronunciation: "yīn yuè" },
  { civilian: "中提琴", spy: "大提琴", civilianTranslation: "Viola", spyTranslation: "Cello", civilianPronunciation: "zhōng tí qín", spyPronunciation: "dà tí qín" },
  { civilian: "流行乐", spy: "摇滚乐", civilianTranslation: "Pop", spyTranslation: "Rock", civilianPronunciation: "liú xíng yuè", spyPronunciation: "yáo gǔn yuè" },
  { civilian: "爵士乐", spy: "蓝调", civilianTranslation: "Jazz", spyTranslation: "Blues", civilianPronunciation: "jué shì yuè", spyPronunciation: "lán diào" },
  { civilian: "古典乐", spy: "歌剧", civilianTranslation: "Classical", spyTranslation: "Opera", civilianPronunciation: "gǔ diǎn yuè", spyPronunciation: "gē jù" },
  { civilian: "足球", spy: "橄榄球", civilianTranslation: "Soccer", spyTranslation: "Football", civilianPronunciation: "zú qiú", spyPronunciation: "gǎn lǎn qiú" },
  { civilian: "篮球", spy: "排球", civilianTranslation: "Basketball", spyTranslation: "Volleyball", civilianPronunciation: "lán qiú", spyPronunciation: "pái qiú" },
  { civilian: "棒球", spy: "垒球", civilianTranslation: "Baseball", spyTranslation: "Softball", civilianPronunciation: "bàng qiú", spyPronunciation: "lěi qiú" },
  { civilian: "网球", spy: "羽毛球", civilianTranslation: "Tennis", spyTranslation: "Badminton", civilianPronunciation: "wǎng qiú", spyPronunciation: "yǔ máo qiú" },
  { civilian: "乒乓球", spy: "壁球", civilianTranslation: "Table Tennis", spyTranslation: "Squash", civilianPronunciation: "pīng pāng qiú", spyPronunciation: "bì qiú" },
  { civilian: "游泳", spy: "跳水", civilianTranslation: "Swimming", spyTranslation: "Diving", civilianPronunciation: "yóu yǒng", spyPronunciation: "tiào shuǐ" },
  { civilian: "跑步", spy: "慢跑", civilianTranslation: "Running", spyTranslation: "Jogging", civilianPronunciation: "pǎo bù", spyPronunciation: "màn pǎo" },
  { civilian: "滑雪", spy: "单板滑雪", civilianTranslation: "Skiing", spyTranslation: "Snowboarding", civilianPronunciation: "huá xuě", spyPronunciation: "dān bǎn huá xuě" },
  { civilian: "滑冰", spy: "冲浪", civilianTranslation: "Skating", spyTranslation: "Surfing", civilianPronunciation: "huá bīng", spyPronunciation: "chōng làng" },
  { civilian: "拳击", spy: "摔跤", civilianTranslation: "Boxing", spyTranslation: "Wrestling", civilianPronunciation: "quán jī", spyPronunciation: "shuāi jiāo" },
  { civilian: "空手道", spy: "柔道", civilianTranslation: "Karate", spyTranslation: "Judo", civilianPronunciation: "kōng shǒu dào", spyPronunciation: "róu dào" },
  { civilian: "长矛", spy: "盾牌", civilianTranslation: "Spear", spyTranslation: "Shield", civilianPronunciation: "cháng máo", spyPronunciation: "dùn pái" },
  { civilian: "弓", spy: "箭", civilianTranslation: "Bow", spyTranslation: "Arrow", civilianPronunciation: "gōng", spyPronunciation: "jiàn" },
  { civilian: "枪", spy: "步枪", civilianTranslation: "Gun", spyTranslation: "Rifle", civilianPronunciation: "qiāng", spyPronunciation: "bù qiāng" },
  { civilian: "国际象棋", spy: "围棋", civilianTranslation: "Chess", spyTranslation: "Go", civilianPronunciation: "guó jì xiàng qí", spyPronunciation: "wéi qí" },
  { civilian: "扑克牌", spy: "麻将", civilianTranslation: "Cards", spyTranslation: "Mahjong", civilianPronunciation: "pū kè pái", spyPronunciation: "má jiàng" },
  { civilian: "拼图", spy: "谜语", civilianTranslation: "Puzzle", spyTranslation: "Riddle", civilianPronunciation: "pīn tú", spyPronunciation: "mí yǔ" },
  { civilian: "机器人", spy: "生化人", civilianTranslation: "Robot", spyTranslation: "Cyborg", civilianPronunciation: "jī qì rén", spyPronunciation: "shēng huà rén" },
  { civilian: "外星人", spy: "怪物", civilianTranslation: "Alien", spyTranslation: "Monster", civilianPronunciation: "wài xīng rén", spyPronunciation: "guài wù" },
  { civilian: "幽灵", spy: "丧尸", civilianTranslation: "Ghost", spyTranslation: "Zombie", civilianPronunciation: "yōu líng", spyPronunciation: "sàng shī" },
  { civilian: "吸血鬼", spy: "狼人", civilianTranslation: "Vampire", spyTranslation: "Werewolf", civilianPronunciation: "xī xuě guǐ", spyPronunciation: "láng rén" },
  { civilian: "龙", spy: "恐龙", civilianTranslation: "Dragon", spyTranslation: "Dinosaur", civilianPronunciation: "lóng", spyPronunciation: "kǒng lóng" },
  { civilian: "魔法", spy: "科学", civilianTranslation: "Magic", spyTranslation: "Science", civilianPronunciation: "mó fǎ", spyPronunciation: "kē xué" },
  { civilian: "梦", spy: "噩梦", civilianTranslation: "Dream", spyTranslation: "Nightmare", civilianPronunciation: "mèng", spyPronunciation: "è mèng" },
  { civilian: "微笑", spy: "大笑", civilianTranslation: "Smile", spyTranslation: "Laugh", civilianPronunciation: "wēi xiào", spyPronunciation: "dà xiào" },
  { civilian: "眼泪", spy: "哭泣", civilianTranslation: "Tear", spyTranslation: "Crying", civilianPronunciation: "yǎn lèi", spyPronunciation: "kū qì" },
  { civilian: "眼睛", spy: "耳朵", civilianTranslation: "Eye", spyTranslation: "Ear", civilianPronunciation: "yǎn jīng", spyPronunciation: "ěr duǒ" },
  { civilian: "鼻子", spy: "嘴巴", civilianTranslation: "Nose", spyTranslation: "Mouth", civilianPronunciation: "bí zi", spyPronunciation: "zuǐ bā" },
  { civilian: "手", spy: "脚", civilianTranslation: "Hand", spyTranslation: "Foot", civilianPronunciation: "shǒu", spyPronunciation: "jiǎo" },
  { civilian: "手指", spy: "脚趾", civilianTranslation: "Finger", spyTranslation: "Toe", civilianPronunciation: "shǒu zhǐ", spyPronunciation: "jiǎo zhǐ" },
  { civilian: "心脏", spy: "大脑", civilianTranslation: "Heart", spyTranslation: "Brain", civilianPronunciation: "xīn zàng", spyPronunciation: "dà nǎo" },
  { civilian: "血液", spy: "汗水", civilianTranslation: "Blood", spyTranslation: "Sweat", civilianPronunciation: "xuě yè", spyPronunciation: "hàn shuǐ" },
  { civilian: "春天", spy: "秋天", civilianTranslation: "Spring", spyTranslation: "Autumn", civilianPronunciation: "chūn tiān", spyPronunciation: "qiū tiān" },
  { civilian: "夏天", spy: "冬天", civilianTranslation: "Summer", spyTranslation: "Winter", civilianPronunciation: "xià tiān", spyPronunciation: "dōng tiān" },
  { civilian: "早上", spy: "晚上", civilianTranslation: "Morning", spyTranslation: "Night", civilianPronunciation: "zǎo shang", spyPronunciation: "wǎn shang" },
  { civilian: "白天", spy: "傍晚", civilianTranslation: "Day", spyTranslation: "Evening", civilianPronunciation: "bái tiān", spyPronunciation: "bàng wǎn" },
  { civilian: "星期一", spy: "星期五", civilianTranslation: "Monday", spyTranslation: "Friday", civilianPronunciation: "xīng qī yī", spyPronunciation: "xīng qī wǔ" },
  { civilian: "一月", spy: "十二月", civilianTranslation: "January", spyTranslation: "December", civilianPronunciation: "yī yuè", spyPronunciation: "shí èr yuè" },
  { civilian: "红色", spy: "蓝色", civilianTranslation: "Red", spyTranslation: "Blue", civilianPronunciation: "hóng sè", spyPronunciation: "lán sè" },
  { civilian: "绿色", spy: "黄色", civilianTranslation: "Green", spyTranslation: "Yellow", civilianPronunciation: "lǜ sè", spyPronunciation: "huáng sè" },
  { civilian: "黑色", spy: "白色", civilianTranslation: "Black", spyTranslation: "White", civilianPronunciation: "hēi sè", spyPronunciation: "bái sè" },
  { civilian: "圆形", spy: "方形", civilianTranslation: "Circle", spyTranslation: "Square", civilianPronunciation: "yuán xíng", spyPronunciation: "fāng xíng" },
  { civilian: "三角形", spy: "长方形", civilianTranslation: "Triangle", spyTranslation: "Rectangle", civilianPronunciation: "sān jiǎo xíng", spyPronunciation: "cháng fāng xíng" },
  { civilian: "直线", spy: "曲线", civilianTranslation: "Line", spyTranslation: "Curve", civilianPronunciation: "zhí xiàn", spyPronunciation: "qū xiàn" }
];
